### ISSUE TITLE
Adding Brother HL-3170CDW to CUPS

### ISSUE THREAD

**Issue by InfoLibre** [OpenPrinting/cups#1014]
I upgraded to Linux Mint Cinnamon 22. My printer doesn't work anymore and I've got this error in /var/log/cups/error_log:

Brother_HL-3170CDW: File \"/usr/lib/cups/filter/brother_lpdwrapper_hl3170cdw\" not available: No such file or directory

Printer drivers are deprecated and will stop working in a future version of CUPS. See https://github.com/OpenPrinting/cups/issues/103

My printer is a Brother HL-3170CDW and I am using LPR and CUPS drivers downloaded on https://www.brother.fr/services-et-supports/hl-3170cdw/downloads

I add lib32stdc++6 32-bit package too: https://github.com/linuxmint/linuxmint/issues/291

Could you publish a new CUPS driver for this printer?

[error_log.zip](https://github.com/user-attachments/files/16372084/error_log.zip)

**Comment by zdohnal** [comment]
No, we don't create and ship printer drivers, with exception to several generic and label printers.

The error message tells you a filter, which is defined by the driver, is missing - both of them have to be provided by the driver.

Your printer looks to have Airprint support - https://support.apple.com/en-us/HT201311 - so it has already support in CUPS. If you have working mDNS resolution and discovery and the printer is in local network, the printer will automatically show up in the print dialog and ready for print.
If mDNS does not work or your printer is not in the local network, you have to install it - take IPP URI (you already use it) and install it with "IPP Everywhere" model in CUPS Web UI or with "-m everywhere" in lpadmin CLI command.
Either way, Airprint has to be enabled on the printer - check printer panel for settings, and enable it if it is disable - otherwise "IPP Everywhere" driver won't work.

If you want to stick with Brother driver, I recommend checking if you installed all driver parts correctly.

**Comment by InfoLibre** [comment]
Thank you. I removed lib32stdc++6 and the two Brother packages and tried your solution, but I've got this error in CUPS (I had this error message with Brother packages too):

![CUPS_5](https://github.com/user-attachments/assets/bd995ec2-e67a-4ced-a8f9-93143a7cecd6)

My configuration:

![configuration imprimante_1](https://github.com/user-attachments/assets/e956f838-c471-41f5-bed0-0dbd227b7767)


![CUPS_1](https://github.com/user-attachments/assets/bb61e0b5-aa5b-4026-bd1f-28474cf5ab23)

![CUPS_3](https://github.com/user-attachments/assets/a57d2c15-9dd8-42e1-ab0b-765e4b697c1a)

![CUPS_4](https://github.com/user-attachments/assets/ce834850-0b69-4d2f-b967-df10792f7930)

**Comment by InfoLibre** [comment]
IPP Everywhere driver is working with my printer without I need to enable AirPrint. Are you sure AirPrint is necessary ?

**Comment by michaelrsweet** [comment]
@InfoLibre A printer that advertises AirPrint support has the necessary support for IPP, DNS-SD, mDNS, and standard file formats. So even when AirPrint is "disabled" the printer probably still supports IPP, DNS-SD, mDNS, and standard file formats (it might just not advertise the AirPrint DNS-SD sub-type).

**Comment by InfoLibre** [comment]
Thank you for the explanations. I disabled AirPrint and mDNS in the printer because I had the printer twice in Linux Mint, even after removing cups-browsed package. I'm only using IPP Everywhere driver and it works perfectly now.
