### ISSUE TITLE
CUPS doesn't print files sent to Brother HL-3170CDW

### ISSUE THREAD

**Issue by InfoLibre** [OpenPrinting/cups#1015]
Following explanations on https://github.com/OpenPrinting/cups/issues/1014, I removed lib32stdc++6 and the two Brother packages and used Airprint. I have this error in CUPS when adding the printer (I had this error message with Brother packages too) but the printer is added. But nothing happens when I'm printing a page, like with Brother drivers, the file is remaining in the queue and the printer is staying in sleeping mode:

![CUPS_5](https://github.com/user-attachments/assets/bd995ec2-e67a-4ced-a8f9-93143a7cecd6)

I've got another computer in the network, with Linux Mint 21.3, printing on the same printer works fine. This bug appeared after upgrading to Linux Mint 22 and new version of CUPS.

My configuration:

![configuration imprimante_1](https://github.com/user-attachments/assets/e956f838-c471-41f5-bed0-0dbd227b7767)

![CUPS_1](https://github.com/user-attachments/assets/bb61e0b5-aa5b-4026-bd1f-28474cf5ab23)

![CUPS_2](https://github.com/user-attachments/assets/f7a8b74f-0d69-4334-9b6d-53aae573a2df)

![CUPS_3](https://github.com/user-attachments/assets/a57d2c15-9dd8-42e1-ab0b-765e4b697c1a)

![CUPS_4](https://github.com/user-attachments/assets/ce834850-0b69-4d2f-b967-df10792f7930)

**Comment by InfoLibre** [comment]
The /var/log/error_log.zip file:
[error_log.zip](https://github.com/user-attachments/files/16379094/error_log.zip)

**Comment by zdohnal** [comment]
The error you see is propagated from a crypto library, CUPS only shows the error which gets from it - my guess Linux Mint 22 tightened crypto settings, and TLS version available on the printer is no longer permitted by system.

I'm not sure what are the settings on Mint regarding cryptography, but we have crypto-policies on Fedora - you will have to ask someone with Mint, if something similar is applied and how to change it, if you want to keep using IPPS.

Or you can try to install the printer with plain IPP (you can modify the schema in URI - ipps -> ipp) and see if it works - IMO it will work, because the error looks really like a crypto one.

If you somehow manage to lower your crypto settings, then you don't have to install the printer at all. The printer will be present in print dialog without any installation in any up-to-date print dialog (PDF viewer, Firefox, Libreoffice, anything using Gtk3, and IIRC even Qt based dialogs support temp queues now).

**Comment by zdohnal** [comment]
Do let me know if either of two (lowering crypto settings and using IPPS, or using plain IPP) works.

**Comment by InfoLibre** [comment]
I activated IPP (port 631) on my printer and it works! Indeed, this old printer is using old SSL versions. I've got the same problem to connect to the printer administration web panel, Firefox is blocking HTTPS. I have no solution excepted using IPP instead of IPPS because Brother support never want to upgrade its old printer firmware. I already asked them to upgrade the printer administration web panel, they refused.
Thank you very much for your help!
