### ISSUE TITLE
Localized strings are not present for many options

### ISSUE THREAD

**Issue by metabiswadeep** [OpenPrinting/cups#1020]
**Describe the bug**
While CUPS provides localized strings for most options, there are still many such ipp options and choices for which CUPS still does not provide localized strings. For example, as in the screenshots below, CUPS does not provide translations for ipp options such as position, page-border, page-set, etc and for their corresponding choices.

**Expected behavior**
CUPS should provide localized strings for these options.

**Screenshots**
![Screenshot 1](https://github.com/user-attachments/assets/3265f303-f971-4918-a6e9-2c113271a8d4)
![Screenshot 2](https://github.com/user-attachments/assets/6f499d90-2ac6-4cfc-9bed-b85acc5c2ebb)

**System Information:**
 - Ubuntu 23.10
 - CUPS version 2.4.6

**Comment by zdohnal** [comment]
Aren't those options+values from PPD file? CUPS localizes only PPD options which generates for IPP Everywhere, and IPP attributes and its values. Other PPD options/values localization have to present in the PPD file to get the localized.

But that's about CUPS - whether the application uses the CUPS locale API to get them localized, that's a different thing.

**Comment by michaelrsweet** [comment]
@zdohnal No, those are CUPS IPP attributes.

@metabiswadeep WRT those IPP attributes, "page-border" is the only one that is not deprecated in CUPS 2.4.x, and it will be deprecated in CUPS 2.5 (haven't gotten around to doing so) since CUPS 3.0 and later won't support it. I'm not sure how much effort we want to put into this but I can see whether adding the strings to be base localization file is enough to propagate things to the other languages, but that is what will be required...

**Comment by michaelrsweet** [comment]
[master ddc560f08] Deprecate page-border Job Template attribute (Issue #1020)

[master a991802ae] Add localizations for deprecated IPP attributes/options (Issue #1020)
