### ISSUE TITLE
Canon Selphy printing from Image Viewer but not from lp command. CUPS 2.4.2

### ISSUE THREAD

**Issue by 7b7bruno** [OpenPrinting/cups#1106]
I am using Raspberry Pi OS (Debian GNU/Linux 12 (bookworm) aarch64) on a Raspberry Pi 5 Model B Rev 1.0.
CUPS version 2.4.2.
I am trying to print pictures on a Canon Selphy CP1500 set up through IPP-USB(compiled latest) with a cable and configured permanently in CUPS with the driver `Canon SELPHY CP1500 HTTP, driverless, cups-filters 1.28.17 (color)`. When I print the pictures from the RPi OS Image Viewer program, they print without a problem, but when I try to print a picture using the `lp` command, The printer shows `Cannot read data! cannot print incompatible images or memory card not readable`. More precisely, I'm using `lp -o media=Postcard.fullbleed -o landscape -o fit-to-page [filename]`, but It does the same thing without the options aswell. What does the Image Viewer do differently compared to the lp command when printing an image? The printer also works fine with windows. I am trying to develop a Java program that prints images and It works on Windows with this exact printer, but not on the Raspberry PI and I assume that It's for the same reasons that the `lp` command doesn't work.

Error log: [error_log.txt](https://github.com/user-attachments/files/18040691/error_log.txt)

Output of **lpstat -e**:
`Canon_SELPHY_CP1500_USB
SELPHY_CP1500`

Output of **lpstat -t**:
`scheduler is running
system default destination: SELPHY_CP1500
device for SELPHY_CP1500: ipp://Canon%20SELPHY%20CP1500%20(USB)._ipp._tcp.local/
SELPHY_CP1500 accepting requests since Fri 06 Dec 2024 05:41:09 PM EET
printer SELPHY_CP1500 is idle.  enabled since Fri 06 Dec 2024 05:41:09 PM EET`

Output of **lpinfo -v**:
`network beh
direct vnc:/
network http
file cups-brf:/
network ipp
direct hp
network socket
network ipps
network https
network lpd
direct hpfax
network ipp://Canon%20SELPHY%20CP1500%20(USB)._ipp._tcp.local/`

There were 2 ppd files for this printer in /etc/cups/ppd: [Selphy_CP1500.ppd.zip](https://github.com/user-attachments/files/18040808/Selphy_CP1500.ppd.zip)

This problem happens with all .jpeg images that I have tried.

D file: [d-file-CP1500.zip](https://github.com/user-attachments/files/18040877/d-file-CP1500.zip)

Output of `lsusb -v`: [lsusb.txt](https://github.com/user-attachments/files/18040911/lsusb.txt)

**ipptool --ippserver attr.log -v ipp://localhost:60000/ipp/print get-printer-attributes.test** returns: `Unable to read response.`

**Comment by zdohnal** [comment]
Hi @7b7bruno ,

thank you for the data!

The logs show "other-error" coming from the printer, however later the printer reports no error when asked, so it gets overwritten...

Either way, driverless backend is covered by the project cups-filters, not CUPS - but I see you have a CUPS temporary queue there ```Canon_SELPHY_CP1500_USB```, which uses IPP Everywhere model from CUPS - does that work correctly?

The ipptool error is strange in comparison to you can see the temporary queue - it is a default request every driverless printer should be able to respond to - it smells like the printer is one of those incapable of a proper response to all+media-col-database request. Do you have the latest firmware updates?

Otherwise please attach logs from /var/log/ipp-usb when you did the ipptool request - @alexpevzner I saw you talked to Bruno on ipp-usb - can you check the ipp-usb logs once Bruno provides them?

So first we need to figure out if the printing works via CUPS, otherwise the issue might lie in cups-filters due driverless backend.

**Comment by alexpevzner** [comment]
Hi @zdohnal,

there are related issues filed against the `ipp-usb`
 * https://github.com/OpenPrinting/ipp-usb/issues/73
 * https://github.com/OpenPrinting/ipp-usb/issues/91

Please, review them too in order to have all information. 

I think the problem at the `cups-filters` side (there were also an "other-error" issue, but it was fixed at the `ipp-usb` side a while ago). Currently I don't see any problems in the `ipp-usb` logs.

Seems also that printer behaves differently when using with the temporary and with the permanent queue.

I'd be glad to merge all these issues into the single one in order to aggregate all available information in a single place, but I don't know how to do that.

**Comment by zdohnal** [comment]
@alexpevzner Since we got this we got the report on CUPS project, I'm going to check if the issue is reproducible in CUPS project - if it is not reproducible, I will pass it to cups-filters/libppd. But you're probably right, it might be in libppd/cups-filters - but if we find out whether IPP Everywhere model is affected or not, we can see what we do in CUPS differently than in cups-filters.
However that get-printer-attributes error from ipptool is weird and that's why I asked you for further review after @7b7bruno provides data only for that request - I don't see any IPP Get-Printer-Attributes logged into ipp-usb log, but I have suspicion the model is another of those incapable of proper Get-Printer-Attributes...

Ad "other-error" - that's what the logs from @7b7bruno shows, probably he did not attach the latest logs or do not have the latest ipp-usb.

@7b7bruno can you apply the latest ipp-usb changes and get a new CUPS debug2 log? So I can see how the logs look like with the latest ipp-usb.

**Comment by zdohnal** [comment]
@alexpevzner looks like ipp-usb does not log incoming IPP requests and printer's responses in detail, it only logs HTTP request and response, but does not go into data part of the packet.

@7b7bruno since that's the case, please attach a file with USB packet capture when you do the IPP request via ipptool - that should get us the data which ipptool gets as response - see https://wiki.wireshark.org/CaptureSetup/USB .

**Comment by 7b7bruno** [comment]
Thank You both for the responses!
I have suspicions that the preinstalled versions of CUPS and IPP-USB are interfering with the compiled ones or preventing them from being installed correctly. I set up Ubuntu on WSL with the CUPS version from APT and It worked without an issue with the exact same Canon Selphy CP1500(even the same USB cable) with the `lp` command. I got pretty great results from It even with borderless printing. But I need to get It working on the Raspberry PI. Can You please guide me towards compiling and installing the newest versions of CUPS and IPP-USB on Raspberry PI OS? I have a feeling I am doing something wrong at this stage. Do I need to do anything more to remove the old versions of CUPS and IPP-USB that come with Raspberry PI OS(than just `apt autoremove`) before compiling and installing the latest from GitHub?

**Comment by alexpevzner** [comment]
Installing ipp-usb should be trivial. If it builds and produces runnable executable, most likely it works correctly.

I guess the problem is somewhere around CUPS settings for the printer, which appears to be different between PC and Raspberry.

**Comment by zdohnal** [comment]
@7b7bruno if you are not experienced with compilation and setting up of SW from source, I would suggest to contact your distro support to help you get the latest CUPS upstream version. CUPS compilation and installation is rather easy, but setting it up to replace system CUPS not so much - you have to be sure to run only the cupsd daemon you've compiled and all things depending on CUPS (like cups-filters) are using the library you manually installed.
Because removing the installed CUPS will remove all dependent packages - so you either have to compile them too if needed, or setup system the way it will use your installed one.

Either way, does the temporary queue work for you?

**Comment by zdohnal** [comment]
Thanks for letting me know!
