### ISSUE TITLE
make install-libs : /usr/sbin/ldconfig permission denied for non-root users

### ISSUE THREAD

**Issue by dkosovic** [OpenPrinting/cups#1122]
With the CUPS 2.5 master branch, after commit https://github.com/OpenPrinting/cups/commit/ac7ddebf29692acb7edb25af70e9bdfcede69dd6 it is no longer possible to run `make install-libs` without getting the following error message:

`usr/sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied`

I think the following `test -x /usr/sbin/ldconfig` condition might need to be in another conditional to test if the Makefile is being invoked with an effective UID (i.e EUID) of 0 :

https://github.com/OpenPrinting/cups/blob/ac7ddebf29692acb7edb25af70e9bdfcede69dd6/Makefile#L218-L220

**Comment by zdohnal** [comment]
Hi @dkosovic ,

I would expect every installation procedure requires sudo or root, since the dirs where library is put needs permissions to write it there.

Additionally IMO running ldconfig is useful there to create necessary links for library to be used later, so IMO this is expected change.

@michaelrsweet WDYT?

**Comment by michaelrsweet** [comment]
The ldconfig step was explicitly added because it is needed for a successful installation on Linux. If you are installing as non-root (either to a private directory or to a build staging area), you might not need to run it but I don't think we can gate it solely on "am I root" - maybe best to just add an "-" to the front of the "if" command so that the exit status is simply ignored.

**Comment by dkosovic** [comment]
For context, I was building a CUPS 2.5 snapshot RPM from a slightly modified Fedora Rawhide `cups.spec` file and it was failing in the `%install` section.

Ignoring the ldconfig error with `-`  in the Makefile before the `if` sounds like a good solution.

**Comment by dkosovic** [comment]
I can confirm that the suggested modification with `-` in the Makefile lets the RPM build to completion.

**Comment by michaelrsweet** [comment]
[master a8408a0b2] Ignore ldconfig errors (Issue #1122)
