### ISSUE TITLE
Testing for accessibility

### ISSUE THREAD

**Issue by ashnansen** [OpenPrinting/cups#135]
It would be nice if the interface could be used through lynx web browser.
https://lynx.invisible-island.net

The Administration page would be nice to use. ;)

**Comment by michaelrsweet** [comment]
Tentatively for 2.4.0, if there is time... :)

**Comment by michaelrsweet** [comment]
Sorry, pushing to 2.5 where we are also going to look at other localization options.

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir this would be my first time contributing to cups, can I work on this?

**Comment by Lord-Morpheus** [comment]
@michaelrsweet is this issue still open? If it is open can I work on this? This would be my first time contributing to CUPS.

**Comment by michaelrsweet** [comment]
@Lord-Morpheus The issue is still open, it was just pushed out of the 2.5 milestone because we didn't have anyone to work on it. If you can do so I'll happily move it back.

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir thank you for your generous offer. I would be happy to work on it but since it is my first time contributing to CUPS, I do not want to jump right into something tough and rather work my way to it. If you can assign some beginner issues that would be nice. If this issue is beginner friendly then I would be glad to do it.

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir how can I get started on this? I am unable to find any readme file which helps me to set up and get started also the contributing.md contains only information on how to establish a pull request. Please help me out. 
Thank you.

**Comment by michaelrsweet** [comment]
The goal of this issue was to make sure the current web interface works from text-based browsers and screen readers. So to work on this you just need to use the web interface at "http://localhost:631" with a text-based browser and/or use screen readers (choose your browser/OS) - keep a log of issues and add them here.

If you know anything about HTML you can also try fixing any issues you find - most of the web interface is in HTML template files (see TRANSLATING.md for details).

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir the "Makefile" which is used in the installation of cups has some unresolved issues due to which I am unable to access "http://localhost:631" in Windows through docker. Right now I am using Ubuntu to check the accessibility in "lynx" browser and I will update you soon with the issues and their fixes.

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir there is one major issue with the interface and that is *The "command line printing and options" link does not render HTML. That means help/options.html is not getting rendered.* Other than this there are many readability issues with table and text alignment which are not proper in 'lynx' web browser. 
I can fix the files but due to an error in "makefile", I am unable to do so.
Shall I try to fix the "makefile" issue?

**Comment by Lord-Morpheus** [comment]
@michaelrsweet shall I fix it?

**Comment by Lord-Morpheus** [comment]
`dnssd.c:30:12: fatal error: avahi-client/client.h: No such file or directory
   30 | #  include <avahi-client/client.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../Makedefs:264: dnssd.o] Error 1
make: *** [Makefile:43: all] Error 1`

This is the error I am receiving after configuring my cups and then executing *make*, as mentioned in INSTALL.md

**Comment by michaelrsweet** [comment]
You need to install the Avahi developer package (libavahi-client-devel on Ubuntu/Debian distros).

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir, there is issue with docker file as the container is not working in windows. The error it gives is `Makefile:12: Makedefs: No such file or directory`. I think this issue needs to be resolved.

**Comment by michaelrsweet** [comment]
@Lord-Morpheus I don't know the status of the docker file in the CUPS repository at the moment, but it needs to run the configure script to create the Makedefs file and it needs all of the prerequisites to successfully do so...

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Sir I have checked all the pages in lynx browser and everything works fine. The readability is pretty low but the rest of everything works as it should. 
Regarding the rendering of the tables I mentioned earlier, it is not a problem because the text-based browsers do not support graphics, therefore, it is displayed correctly.

**Comment by michaelrsweet** [comment]
@Lord-Morpheus Thanks for the testing, I'll call this close as fixed.

**Comment by Lord-Morpheus** [comment]
@michaelrsweet Is there any other issue that I can work with or is there any new feature that needs to be added on which I can work on?

**Comment by Lord-Morpheus** [comment]
@tillkamppeter @michaelrsweet, Sir Is there any other issue that I can work with or is there any new feature that needs to be added on which I can work? I work with Windows OS so it would be preferred if the work could be done with the docker on Windows.

**Comment by michaelrsweet** [comment]
@Lord-Morpheus There is some work being done to support CUPS as a standard Docker container, which might be a good fit for you? Otherwise the remaining tasks are more technical in nature...

**Comment by Lord-Morpheus** [comment]
@michaelrsweet As it would help me to increase my knowledge about docker containers I would be happy to do this task. Please help me to get started with this.

PS.  How can I contact you for further issues since this is a closed issue I guess it would be better if we have a chatroom to resolve problems or shall I contact you via Email?

**Comment by tillkamppeter** [comment]
Hi, @Lord-Morpheus , thanks for your interest in OpenPrinting.

To get some general introduction into our work, have a look here, especially also the videos in the beginning:

https://wiki.linuxfoundation.org/gsoc/google-summer-code-2024-openprinting-projects#introduction

The page also shows what we are doing this year in the Google Summer of Code (on most of the posted ideas we actually have a contributor working).

Monthly news blog posts on: https://openprinting.github.io/news/

In terms of OCI containerization we have also a GSoC contributor working, currently on a CUPS image, and he is building it with rockcraft. If you are interested to help out, join the Telegram channel:

https://t.me/+35KCEXUqC-w2M2Q0

Topics where I am eagerly looking for help:

- Documentation for the libraries:

https://github.com/OpenPrinting/libcupsfilters/issues/54

- General bug work, especially libcupsfilters and cups-filters

- KDE desktop integration  of the New Architecture/CUPS 3.x:

https://openprinting.github.io/OpenPrinting-News-April-2024/#kde-print-manager

We have also a general chat channel for OpenPrinting, also on Telegram:

https://t.me/+RizBbjXz4uU2ZWM1

**Comment by Lord-Morpheus** [comment]
@tillkamppeter After reading the content you provided I would like to work on "KDE desktop integration of the New Architecture/CUPS 3.x" as first preference, "Documentation for the libraries" as second preference and "general bug work" as third preference.
