### ISSUE TITLE
lpadmin and foomatic-rip not found after installing CUPS 2.2.1 on AIX 7.1 

### ISSUE THREAD

**Issue by yuanqiong-ricoh** [OpenPrinting/cups#150]
Since we want to implement IPPS printing on the AIX OS, we want to build a CUPS environment on the AIX OS, using the yum tool, CUPS 2.2.1 was installed, but the following problems occurred:

1.When using the lpadmin command, the following error occurred

 //# lpadmin
 //ksh: lpadmin: not found.
 //# whereis lpadmin
 //lpadmin:
 //#

2.The following error appears after installing the PPD driver and Print test page:
 "File "/opt/freeware/lib/cups/filter/foomatic-rip" not available: No such file or directory"

We checked the installation files, lpadmin and foomatic-rip did not seem to be installed.

What we want to know:

1.Which CUPS package does lpadmin exist in, and how do we solve this problem?
 Below are the package installed
 cups.ppc 2.2.1-1 @perzl.org
 cups-client.ppc 2.2.1-1 @perzl.org
 cups-devel.ppc 2.2.1-1 @perzl.org
 cups-ipptool.ppc 2.2.1-1 @perzl.org
 cups-libs.ppc 2.2.1-1 @perzl.org
 cups-lpd.ppc 2.2.1-1 @perzl.org

2.foomatic-rip seems to exist in the CUPS-filter package. Which is the CUPS-filter package corresponding to CUPS2.2.1 and where can we download it?

**Comment by zdohnal** [comment]
Hi,

> Since we want to implement IPPS printing on the AIX OS, we want to build a CUPS environment on the AIX OS, using the yum tool, CUPS 2.2.1 was installed, but the following problems occurred:

If you mean implementing in terms of coding it, there's no need. CUPS implements IPPS printing AFAIK.

> 1.When using the lpadmin command, the following error occurred
> 
> //# lpadmin
> //ksh: lpadmin: not found.
> //# whereis lpadmin
> //lpadmin:
> //#
> 

If you are on RH/RH derived distro, ```lpadmin``` is in ```cups-client``` package. Since it looks you have it installed, then the problem is in you PATH environment variable or the package installs ```lpadmin``` somewhere outside of reach of ```PATH```.
It lives in ```/usr/sbin``` on normal RH distro, so it depends where your package provider put the binary or how you set your ```PATH```.

> 2.The following error appears after installing the PPD driver and Print test page:
> "File "/opt/freeware/lib/cups/filter/foomatic-rip" not available: No such file or directory"
> 

```foomatic-rip``` can live in one of two packages - depends how old your distro is - RHEL/CentOS 7 and older it is ```foomatic-filter``` package, RHEL/CentOS 8 and newer it is ```cups-filters``` package.

But neither of them puts ```foomatic-rip``` into ```/opt/freeware``` dir.

> We checked the installation files, lpadmin and foomatic-rip did not seem to be installed.
> 
> What we want to know:
> 
> 1.Which CUPS package does lpadmin exist in, and how do we solve this problem?
> Below are the package installed
> cups.ppc 2.2.1-1 @perzl.org
> cups-client.ppc 2.2.1-1 @perzl.org
> cups-devel.ppc 2.2.1-1 @perzl.org
> cups-ipptool.ppc 2.2.1-1 @perzl.org
> cups-libs.ppc 2.2.1-1 @perzl.org
> cups-lpd.ppc 2.2.1-1 @perzl.org
> 

As I wrote before, depends on your distro. RH/RH derived OSes have it in cups-client, but since it is installed, look into your PATH variable or contact your OS support.

> 2.foomatic-rip seems to exist in the CUPS-filter package. Which is the CUPS-filter package corresponding to CUPS2.2.1 and where can we download it?

cups-filters is a separate project so it is mostly (with exception for CUPS major version 1) not limited by CUPS version.
The package usually a dependency of cups, so your cups package provider should have it too.
