### ISSUE TITLE
No grayscale option when using ipp everywhere

### ISSUE THREAD

**Issue by tiiiecherle** [OpenPrinting/cups#151]
Thanks for continuing this project here.

Unfortunately [https://github.com/apple/cups/issues/5768](https://github.com/apple/cups/issues/5768) is still not working with the latest release.

Thanks for looking into it in advance.

**Comment by zdohnal** [comment]
Hi @tiiiecherle ,

would you mind telling me which CUPS version did you try?

**Comment by tiiiecherle** [comment]
Hey @zdohnal,

I tried with macOS 11.2.3.

```
cups-config --version
2.3.4
```

I also tried installing another version via homebrew
`brew install --formula cups`

This installs the following version:
```
brew info cups
cups: stable 2.3.3op2 (bottled), HEAD [keg-only]
Common UNIX Printing System
https://github.com/OpenPrinting/cups
/usr/local/Cellar/cups/2.3.3op2 (119 files, 9.1MB)
```

My PATH in `~/.zshrc` looks like this:
`export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/opt/openssl@1.1/bin:$PATH"`

Is there anything else to do to make macOS use version 2.3.3op2 or is it already using it?

Thanks

**Comment by zdohnal** [comment]
Ok, to be honest, I'm not a MacOS user, so I'm not sure how brew works and if the software installed by it is accessible by default... I would check f.e. ```lpadmin``` command if it comes from the correct location - ```/usr/local/Cellar/cups/2.3.3op2``` by:

```
$ which lpadmin
```

but I'm not sure if it works on Mac.

Would anyone with Mac experience mind looking into the ticket?

**Comment by tiiiecherle** [comment]
@zdohnal 
Thanks.

```
which lpadmin
/usr/sbin/lpadmin
```

It seems it does not use the homebrew version.

As I understand from this it has to be added to the PATH specifically.

```
brew info cups
cups: stable 2.3.3op2 (bottled), HEAD [keg-only]
Common UNIX Printing System
https://github.com/OpenPrinting/cups
/usr/local/Cellar/cups/2.3.3op2 (119 files, 9.1MB)
  Poured from bottle on 2021-03-13 at 11:09:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cups.rb
License: Apache-2.0
==> Options
--HEAD
	Install HEAD version
==> Caveats
cups is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have cups first in your PATH, run:
  echo 'export PATH="/usr/local/opt/cups/bin:$PATH"' >> ~/.zshrc

For compilers to find cups you may need to set:
  export LDFLAGS="-L/usr/local/opt/cups/lib"
  export CPPFLAGS="-I/usr/local/opt/cups/include"

==> Analytics
install: 126 (30 days), 330 (90 days), 937 (365 days)
install-on-request: 125 (30 days), 330 (90 days), 934 (365 days)
build-error: 0 (30 days)
```
I would try it like this:
`export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/cups/bin:$PATH"`

If there is anyone to help and can tell me if this looks right it would be nice.

I do not have the connection to try right now but I will try in the next days and report back.

Thanks

**Comment by michaelrsweet** [comment]
@tiiiecherle Due to a variety of security features of current macOS releases, it is basically impossible to replace the version of CUPS that comes with macOS. System Integrity Protection (SIP) enforces a read-only system partition which prevents you from replacing most of the CUPS files, including libcups (which has the PPD generator). If you disable SIP, the Secure Runtime feature (enforced through code signing) will cause you to "brick" your system because you can't codesign libcups as Apple - I'm not sure those checks can be disabled. And then finally any software update that includes CUPS will wipe out any changes you make. So please don't try to *install* a different version of CUPS - you'll just be giving yourself a bad day.

So, that said there are three solutions for you:

1. Use the Apple-supplied Print & Scan preference pane (or the Print dialog) to add this printer. This printer supports AirPrint, which is the equivalent of IPP Everywhere on macOS and iOS.
2. Use the Brew version of CUPS you've installed by typing the full path to lpadmin (`/usr/local/Cellar/cups/2.3.3op2/usr/sbin/lpadmin`) - I'm not sure whether this will work since it might try to use a different domain socket.
3. Compile CUPS from source yourself with the `--disable-shared` configure option. *Do not install it* but instead run the lpadmin program from the source directory (`systemv/lpadmin`)

Option #1 is almost certainly the easiest approach.

**Comment by tiiiecherle** [comment]
@michaelrsweet
@zdohnal 
First of all thanks for the fast feedback, but please re-open the ticket until it is really solved and currently it is not.

1. The airprint driver for our printer is also lacking a lot of features and we are preparing all our macs with an install script and we would like to remain using the command line to add the printer.
2. using this
`export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/cups/bin:$PATH"`
helps with 
```
cups-config --version
2.3.3op2
```
but lpadmin is still the same
```
which lpadmin
/usr/sbin/lpadmin
```

Using find on the whole drive there is only one lpadmin available and the issue still persists..

3. Sorry, I don't know how to do that.

I still think this is an issue and should be further investigated as it is not solved.

Using a PPD file gives you more options in the printing dialog that are clearly missing using ipp everywhere.

Thanks

**Comment by michaelrsweet** [comment]
@tiiiecherle The Github issues are not a support forum or mailing list (we're working on adding one, BTW). And in particular macOS has its own version of CUPS and its own support provider (Apple, <https://bugreport.apple.com> or Feedback Assistant) that will be able to respond definitively. In particular, the AirPrint driver *should* expose every feature the printer has over IPP. This may be different than the options you'll see on Windows clients, for example, and often is slightly different than the IPP Everywhere PPD mainly because AirPrint PPDs use a special Print dialog extension to show the driver options (instead of the fallback "Printer Features" UI). And of course a regular CUPS printer driver from the vendor (Canon in this case) will likely have its own Print dialog extension(s) and additional options that are not present in the IPP Everywhere or AirPrint drivers.

WRT deploying printers to multiple Mac, Apple *does* provide a way to setup printers using configuration profiles that can be deployed to all of your Macs - see the Apple Configurator application. If you really want to roll your own solution, setup the printer on one Mac and copy the PPD file to use with your scripts.

If a `find /usr/local -name lpadmin` turns up empty then you are missing part of the CUPS installation. I don't know how Brew packages CUPS, but you might try asking *them* for assistance...
