### ISSUE TITLE
Barcode is printing with low quality

### ISSUE THREAD

**Issue by kamiszczu** [OpenPrinting/cups#178]
I have a printer zebra420. The problem is that barcode on label is printing with low quality.

I testing with two version and on both is another quality. Printing from windows is every good.

Attached three pictures:

Printing from:

**Windows via driver from zebra**

![windows_driver_zebra](https://user-images.githubusercontent.com/5055672/115726735-49da0400-a383-11eb-96b6-7c7ec0270813.PNG)

**CUPS 2.2.10**
![CUPS 2 2 10](https://user-images.githubusercontent.com/5055672/115726737-4a729a80-a383-11eb-87d3-69ff08ca9599.PNG)

**CUPS 2.3.3op2**
![CUPS 2 3 3op2](https://user-images.githubusercontent.com/5055672/115726739-4b0b3100-a383-11eb-9cfc-56b2f75268ab.PNG)

How resolve this problem?

**Comment by michaelrsweet** [comment]
@kamiszczu The issue here is a combination of low resolution (203 dpi) and the anti-aliasing behavior of the various PDF rasterization filters used. Basically, you either have anti-aliasing enabled and you get fuzzy, dithered output or you have anti-aliasing turned off and lose the spacing between the lines.

Unfortunately there is nothing that can be done with the current driver - it asks for 1-bit B&W raster data and prints it as-is. I am working on a potential fix for this in the [LPrint](https://github.com/michaelrsweet/lprint) label drivers which I *hope* will be released in the coming month...

**Comment by ValdikSS** [comment]
If you print from PDF, cups-filters 1.x git and libcupsfilters git master `gstoraster` (not in released versions yet) now has bi-level threshold mode, as well as other halftoning and dithering options.

https://github.com/OpenPrinting/cups-filters#ghostscript-rendering-halftoning-and-dithering

Use

```
lpadmin -p your_printer_name -o halftone-type-default=bi-level -o center-of-pixel-default=true
```

to set sane defaults for barcode and QR code printing.

Bi-level halftoning is also supported in `imagetoraster`, which is used when printing JPEG or PNG.
