### ISSUE TITLE
Null dereference in ippWriteIO for value collection

### ISSUE THREAD

**Issue by catenacyber** [OpenPrinting/cups#195]
Found by fuzzing
Getting the crash with `./fuzzipp crash-e1a5e250cf0fa5a27edc86104712940cedd80eab`
with crash-e1a5e250cf0fa5a27edc86104712940cedd80eab being a file whose base64 encoding is `MQC6vhm6OgAINAAC7gcw`

A simple fix may be
```
diff --git a/cups/ipp.c b/cups/ipp.c
index 3a341f217..a52d6621e 100644
--- a/cups/ipp.c
+++ b/cups/ipp.c
@@ -6024,7 +6024,11 @@ ippWriteIO(void       *dst,              /* I - Destination */
                  /*
                  * Then write the collection attribute...
                  */
-
+            if (value->collection == NULL) {
+                DEBUG_puts("1ippWriteIO: No collection to write value");
+                _cupsBufferRelease((char *)buffer);
+                return (IPP_STATE_ERROR);
+            }
                   value->collection->state = IPP_STATE_IDLE;
 
                  if (ippWriteIO(dst, cb, 1, ipp,
```

**Comment by michaelrsweet** [comment]
@catenacyber Thanks for reporting this. It should not be possible to get a NULL collection value from reading an IPP message, so the correct fix needs to be in the `ippReadIO` function. Investigating...

**Comment by michaelrsweet** [comment]
@catenacyber OK, so this isn't something that would affect (crash) cupsd or any other IPP server using libcups since we would never echo back a broken message like this. The simple solution is to delete the pending (new) attribute once we see that the value cannot be read:

[master 655ed2928] Delete an empty attribute if we aren't able to get the value length, otherwise the IPP message will contain a truncated attribute that cannot be written (Issue #195)
