### ISSUE TITLE
How to Over-ride printer-uri ?

### ISSUE THREAD

**Issue by iam-TJ** [OpenPrinting/cups#203]
We have a Samsung CLX-6220FX Colour LASER multifunction printer that supports draft IPP v1.1 circa 2008 connecting via Ethernet. It supports IPv4 and IPv6. We operate an IPv6-only network and have discovered a bug in the printer firmware that we need to work around.

Specifically, although the printer listens on its IPv6 addresses it has a bug where it expects the `printer-uri` embedded in requests to contain its IPv4 URI! When the IPv6 URI is used the response is `client-error-not-found`.

We have proved, using `ipptool -d uri2=$IPv4_URI  ipp://$IPv6_URI/?version=1.1 get-print-attributes-debug.test` (our modified test script that uses `ATTR uri printer-uri $uri2`, that the printer will respond correctly if we embed the IPv4 URI in requests. 

We need some advice on how we can over-ride this in CUPS whether through some configuration change or modifying the source and rebuilding. There appears to be code handling `printer-uri` in `cups/dest.c` but not being familiar with the codebase it isn't clear precisely what changes we'd need to make to ingest some custom configuration value and use it at this low level.

**Comment by michaelrsweet** [comment]
@iam-TJ There isn't a way to pass a different URI for general CUPS printing. If the printer has a mDNS hostname (something.local) you might be able to use that instead (and that will auto-switch between IPv6 and IPv4) but your better bet with this printer is just to use AppSocket (`socket://[ipv6-address]:9100`) since it doesn't properly support IPP.
