### ISSUE TITLE
Planning: Centralize CUPS localization

### ISSUE THREAD

**Issue by fitojb** [OpenPrinting/cups#216]
To ease the updating of translations, I suggest using Weblate, either its SaaS ("Hosted") instance or a dedicated server install.

**Comment by michaelrsweet** [comment]
@fitojb Several solutions for this have been proposed, but so far none of them have panned out even for test projects. I'll leave this open for now, as I know that most Linux distributions have their own contributed localizations that are added to their CUPS packages. Ideally those should be merged to OpenPrinting CUPS so we have everything in one place.

Complicating matters is the fact that CUPS has both gettext-style "po" files as well as web interface templates that need to be localized.

**Comment by yarons** [comment]
I totally understand your point, so the situation is this:
Contributing to the CUPS package on Ubuntu is managed via Launchpad (Rosetta), a web translation platform.
Fedora's translation (although there's no CUPS override) are managed via their own Weblate instance.

A web localization platform will ease the contribution so that translators with lots of lingual experience and less technical experience will be able to contribute upstream.
BTW Canonical are encouraging the contributors to upload their changes upstream, they're not doing it automatically becuase it may lead to some conflicts but they are offering the localization files for download, that way you can merge the localization back if required but doing it automatically is just too complicated.

I've managed to set up Crowdin for this task, it's working pretty good for me but it's not open source so I'm against this solution sadly.

I have some really good connection with the Weblate management team and I'm guessing it would be a great honor for them to host the CUPS localization efforts officially, should I make the connection between the two of you?

Thanks!

**Comment by michaelrsweet** [comment]
@yarons I appreciate the offer and will circle back when we are ready to tackle this after 2.4.0 is out.

**Comment by yarons** [comment]
I heard the news about 2.5.0 and 3.0 (Phoronix snitched 😄), thank you so much for this wonderful system! We'll keep in touch.

**Comment by zdohnal** [comment]
I got [Fedora Weblate](https://translate.fedoraproject.org) set on system-config-printer project and once I've become an admin of the project there, it is easy to maintain the translations.

If Yaron is busy in the future, people with admin rights are available on trans@lists.fedoraproject.org and can help us (when I had problem, someone responded in matter of minutes on the list).

So if we go this way, we will need someone who will create the repository on Fedora Weblate and don't forget to set us as an admin of the repository - because sometimes you can hit merge conflicts - in cases when you merge new translations (by PR from Weblate) in github project and someone, who is currently translating in Weblate, doesn't refresh the repository and push the new translations.

**Comment by yarons** [comment]
I'm friends with the guys there, it's a wonderful idea.

**Comment by zdohnal** [comment]
Ok, once we are on the same page whether we use the same Weblate, I'll reach for help on Fedora translations mailing list.

**Comment by yarons** [comment]
@zdohnal Thanks for the offer, @nijel is the guy behind Weblate, I'm hoping we'll see some progress in the next couple of days.

**Comment by zdohnal** [comment]
Ok, since Mike used the Hosted Weblate instead of Fedora version, I don't have any connections there. But since Mike was able to set the project there, it probably has more free conditions.

**Comment by michaelrsweet** [comment]
OK, things are now setup via a [hosted Weblate](https://hosted.weblate.org) project.

**Comment by NorwayFun** [comment]
Hello,
Is anyone actually syncing translations from Weblate, please?

**Comment by michaelrsweet** [comment]
@NorwayFun Investigating, something has definitely f'd up on the Weblate side (should be auto-merging updates from Github...)

**Comment by NorwayFun** [comment]
Any news, please?

**Comment by michaelrsweet** [comment]
@NorwayFun Sorry, I've been trying to coax the Weblate repository to update things but because some localization has happened there and some *here*, it has gotten confused. The only remaining option appears to be to nuke the Weblate localizations repository which I am hesitant to do since there is work there that is not yet reflected in the CUPS repository.

**Comment by nijel** [comment]
> Investigating, something has definitely f'd up on the Weblate side (should be auto-merging updates from Github...)

Weblate is not receiving notifications of repository updates, so it can't auto-merge them. Needs to be configured on GitHub side, see https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

Moreover, you might want to configure automatic pushing changes from Weblate, see https://docs.weblate.org/en/latest/admin/continuous.html#push-changes

Both these are suggested at https://hosted.weblate.org/guide/cups/cups/

I've now merged upstream changes into Weblate repository manually (this caused discarding some changes in the Polish translation in Weblate because different changes were done in the repository), so it should be possible to merge the changes back. But without automating this (see above), things will diverge again.

**Comment by michaelrsweet** [comment]
@nijel I've updated the CUPS repository with the specified changes. Seems like things are still stuck on a conflict in the German translations... :(

**Comment by nijel** [comment]
Rebase will not work, but the changes are merged with a merge commit. Fixing rebase would need more work.

**Comment by NorwayFun** [comment]
Hello everyone,
Any update on this, please? :)
