### ISSUE TITLE
ZP 505 prints blank

### ISSUE THREAD

**Issue by dukenukemx** [OpenPrinting/cups#265]
On Linux Mint 20 using CUPS 2.3.1 my ZP 505 which shows up as ZTC ZP 500 (ZPL) prints blank.  It works fine on Windows using the supplied driver.

**Comment by michaelrsweet** [comment]
@dukenukemx How is the printer connected to your system? How have you configured the driver?

**Comment by dukenukemx** [comment]
I have it connected via USB.  When I configure it I select ZPL.

**Comment by zdohnal** [comment]
No response and no data for two weeks, closing for now.

**Comment by MaffooClock** [comment]
My apologies for digging up an old grave, but I have the same problem and this is the only resource I've found (so far).  Too bad this was closed due to lack of response.

I've just run into exactly this issue with the same ZP505 printer -- everything appears to behave as expected, just the label is blank.  Here are the two files that were requested:

- [current_log.txt](https://github.com/OpenPrinting/cups/files/15341549/current_log.txt)
- [Zebra_ZP_505.ppd.txt](https://github.com/OpenPrinting/cups/files/15341550/Zebra_ZP_505.ppd.txt)

I didn't see any obvious errors, although I haven't thoroughly scrutinized it, either (yet).  One thing I noticed is that it takes almost a minute from the time the job appears in the queue until it actually prints... maybe that's normal and is unrelated to this issue, I don't know.

It has a roll of 4" x 6" direct thermal labels loaded, and it has been calibrated for those labels (hold down feed button until LED blinks twice), and feeding looks accurate.  Also, I can print the config (hold down feed button until LED blinks once), so I know the machine itself is capable of printing.

![Screenshot 2024-05-16 at 17 27 56](https://github.com/OpenPrinting/cups/assets/540782/b65b56cd-9373-4313-8716-b727d5b4f9e1)

![IMG_8869](https://github.com/OpenPrinting/cups/assets/540782/97bbb5e3-f463-4e1e-ad98-8fb2fbb0e629)

**Comment by dukenukemx** [comment]
I solved the problem a while ago.  The driver that works is Zebra EPL2 Label Printer.  Even though it says ZP 505 on the printer, doesn't mean you should select ZP 500 as the driver.  I'm using Linux Mint 21.3 and EPL2 driver selected works.  It's stupid is all I can say.

**Comment by MaffooClock** [comment]
> ZP 500 as the driver

I think you mean ZPL here, which is what I was using.

But yes, I changed the driver from ZPL to EPL2, and voila, it worked.  Thanks for the tip 👍

**Comment by dukenukemx** [comment]
> > ...ZP 500 as the driver
> 
> I think you mean ZPL here, which is what I was using.
> 
> But yes, I changed the driver from ZPL to EPL2, and voila, it worked. Thanks for the tip 👍

That's what I meant.  Glad to hear it works.  I'm not sure if this is because the names of the drivers aren't intuitive or because the driver name isn't correct?

**Comment by michaelrsweet** [comment]
@dukenukemx @MaffooClock The driver name is correct but perhaps there is an issue with the printer not recognizing the ZPL preamble? Most Zebra printers understand both ZPL and EPL2 (page mode) but the test page clearly shows that the ZP505 also supports ZPL...

FWIW, the output from [LPrint](https://www.msweet.org/lprint) is generally superior to the old CUPS sample drivers, and I'd be interested to know if LPrint has the same issue with the ZP505...

**Comment by MaffooClock** [comment]
> I'd be interested to know if LPrint has the same issue with the ZP505

Interesting... I'm setting up a Raspberry Pi with CUPS and an old ZP 505 for the sole purpose of printing shipping labels (typically images or PDFs, not from WorldShip or ShipManager), so LPrint might be closer to what I needed in the first place.
