### ISSUE TITLE
Scanner does not work in SCX-3405W after printing with CUPS

### ISSUE THREAD

**Issue by jpalus** [OpenPrinting/cups#270]
I've got a multi-function printer/scanner device Samsung SCX-3405W and noticed that after first page is printed in CUPS scanner stops responding. It appears to be caused by quirk for all Samsung printers:
```
# All Samsung devices (https://bugs.launchpad.net/bugs/1032456)
0x04e8 soft-reset
```
Not really sure why it was applied so broadly but after disabling it printing works perfectly fine as well as scanning.

**Comment by zdohnal** [comment]
Hi @jpalus ,

thank you for reporting the issue!

It would be great if you entered ```lsusb``` command on your machine and pasted the output here in the issue - we will need vendor and product IDs for whitelisting your device, since it works without a quirk.
And then I will need a help from you, because we will need to verify the change, which will be different than what you proposed - removing the lines you mentioned can break printing for others, so I will try to propose to whitelist your printer model.

@michaelrsweet my idea is to get vendor and product IDs of the device and then put it into ```backend/org.cups.usb-quirks``` with ```whitelist``` keyword - the new entry will need to be after the generic Samsung rule to have an effect. WDYT? Should I look out for something else?

**Comment by jpalus** [comment]
@zdohnal: relevant entry from `lsusb`:
```
Bus 004 Device 002: ID 04e8:344f Samsung Electronics Co., Ltd SCX-3400 Series
```

Regarding solution I've been thinking about it and came to similar solution to yours but a little more extended so it's a bit easier to customize for a user:
1. add `no-quirks` keyword (same as your `whitelist`)
2. allow quirks to be added by user and loaded ie from `/etc/cups/usb/org.cups.usb-quirks` (would require searching for existing quirk instead of always adding new one)
3. allow multiple quirk keywords so it's possible to override quirk in just one line ie `04e8 no-quirks no-reattach` (made-up example)

**Comment by zdohnal** [comment]
> ```
> Bus 004 Device 002: ID 04e8:344f Samsung Electronics Co., Ltd SCX-3400 Series
> ```

Thank you for the data!

> 
> Regarding solution I've been thinking about it and came to similar solution to yours but a little more extended so it's a bit easier to customize for a user:
> 
>     1. add `no-quirks` keyword (same as your `whitelist`)

I don't see a reason why a new keyword should be added.

> 
>     2. allow quirks to be added by user and loaded ie from `/etc/cups/usb/org.cups.usb-quirks` (would require searching for existing quirk instead of always adding new one)
> 

Doable even now - I have ```/usr/share/cups/usb/org.cups.usb-quirks``` file in Fedora, where new quirks can be added.

>     3. allow multiple quirk keywords so it's possible to override quirk in just one line ie `04e8 no-quirks no-reattach` (made-up example)

As you can see in the mentioned file, a list of quirk keywords are already supported.

===============================================================

Would you mind putting the original line back:

```
# All Samsung devices (https://bugs.launchpad.net/bugs/1032456)
0x04e8 soft-reset
```

then put right under it:

```
# Samsung SCX-3405W
0x04e8 0x344f whitelist
```

and try to print?
