### ISSUE TITLE
Poor user experience adding new paper sizes to printers

### ISSUE THREAD

**Issue by fedorowp** [OpenPrinting/cups#292]
End users sometimes need to add new paper sizes to printers.

The de facto directions is in Stack Overflow post https://stackoverflow.com/questions/1028891/whats-the-easiest-way-to-add-custom-page-sizes-to-a-ppd/3112256

End users needing to sift through answers to find one which then involves adding four different entries to a 1000+ line .ppd files provides a poor user experience.

A CUPS web interface capability is needed for adding paper sizes, or at least a command-line tool.

**Comment by zdohnal** [comment]
Hi @fedorowp ,

thank you for the input.

However, CUPS main purpose is not to be a driver editor - usually nowadays (and it will be the only way in the near future) CUPS gets such information from a printer, other CUPS server or printer application via IPP protocol.

If there is an incorrect or a missing page size, please report it to your driver provider with a patch. Then the provider (manufacturer, community, distribution) can share the fixed drivers among everyone else.

The verified patch is usually a requirement (unless the driver provider is a printer manufacturer), because there is a huge chance that community or distro maintainer don't have your printer model, and if upstream is unresponsive, they don't have any other way how to verify the patch than via reporter.

If we actually decide to tackle this feature, IMO it might be in printer applications, or in their common library - PAPPL. @tillkamppeter @michaelrsweet thoughts?

**Comment by tillkamppeter** [comment]
Another approach would be that whenever a printer reports that it supports custom paper sizes (via IPP or the PPD file) the print dialog could not only allow the user to enter the size but to save sizes and give them names, so that he has his preferred extra sizes at hand. This would be a nice feature request for te print dialogs.
