### ISSUE TITLE
cups-2.3.3op2: Bad permissions for USB connected printers

### ISSUE THREAD

**Issue by pacho2** [OpenPrinting/cups#314]
Hello,

This is an old issue that is still happening and I am unsure about how to fix it finally and for all the people. The main issue is that the device assigned to the USB printer gets wrong permissions. In my case, it's being assigned to scanner group (probably because it is a printer+scanner device):
$ ls -l /dev/bus/usb/001/004 
crw-rw-r--+ 1 root scanner 189, 3 dic 24 12:37 /dev/bus/usb/001/004

The consequence is that jobs get stuck with "Waiting for printer to become available" error forever.

Workarounds are posted in internet for many different distributions, in summary, the solution is to manually create a udev rule to fix the permissions, as explained at:
https://wiki.gentoo.org/wiki/Printing#USB_Printer_is_not_detected
https://www.linuxquestions.org/questions/slackware-14/waiting-for-printer-to-become-available-4175652261/
https://www.reddit.com/r/linuxquestions/comments/riqf4n/cant_print_waiting_for_printer_to_become_available/
https://wiki.archlinux.org/title/CUPS/Troubleshooting#Bad_permissions
https://forums.gentoo.org/viewtopic-t-1095586-highlight-.html
https://bugs.gentoo.org/644636

But, ideally, we shouldn't rely on users needed to do this on their own and it should just work

Thanks a lot for your help

**Comment by pacho2** [comment]
I reported it also to sane-backends as, *in my case*, the change of permission is caused by a udev rule from them. For other people there were other packages changing the permissions and, later, printing failing as cups doesn't try to ensure the permissions are correct for printing (or maybe it should allow other known groups like "scanner" and not only "lp"... ) 

The sane-backends bug is:
https://gitlab.com/sane-project/backends/-/issues/546

**Comment by zdohnal** [comment]
Hi @pacho2 ,

I don't know what mechanism is used on Mac OS, but on some Linux distributions (I've checked it on my Fedora installation, so its derivatives can be similar) systemd sets root:lp ownership and group membership on the specific usb device and AFAIK CUPS itself doesn't change the permissions or adjusts ACL.

From the links you've provided I see the issue is usually triggered by 3rd party package overriding the owner:group settings from kernel/systemd and by systemd bug, which caused the initial root:lp settings weren't applied.

So IMO the proper fix should happen in the packages which overrides the settings from kernel/systemd - f.e. use ACLs instead of hard override of group membership to a new value.

Additionally usb backend will go away in near future due full transition to IPP and IPP-over-USB communication, so IMO any possible workarounds should rather be applied in printer applications and ipp-usb project.

**Comment by pacho2** [comment]
Well... that package in collision is sane-backends... hence it will keep hitting all the combined printers+scanner 

Aren't you having this issue in Fedora? Last time I checked they were also installing the probably bogus sane-backends .rules file that would lead into this issue

**Comment by zdohnal** [comment]
@pacho2 sane-backends in Fedora doesn't use the pregenerated udev rules from ```tools/udev``` directory, but it runs ```sane-desc``` after ```make build``` to create a new udev rules (using ```udev+hwdb``` mode, which doesn't use the scanner group) and those are packaged. So no rules which change group of the device are packaged.

**Comment by pacho2** [comment]
Thanks, I will try to follow that in our Gentoo ebuild

Best regards
