### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by CarlSchwan** [OpenPrinting/cups#315]
Hi 👋

I wanted to let you know that it seems Microsoft forked this repo and changed the license to the MIT license in their fork and are claiming to have copyright to this repo (Copyright (c) Microsoft Corporation.)

https://github.com/microsoft/cups/commit/ad69bcc78bdea3fea3f09fe56674daea821bb407

INAL but this seems to be a copyright violation.

**Comment by aloisdg** [comment]
Related to [grpc_bench](https://github.com/microsoft/grpc_bench/commit/04c7143a39a0bb243369e31f3b3b797449468fdb)

**Comment by 6uhrmittag** [comment]
For reference, the current Hacker News discussion: https://news.ycombinator.com/item?id=29683471

It's worth noting that some comments suspect it to be a misconfigured bot action.

**Comment by madscientist42** [comment]
The problem **_I_** happen to have with that take?  That this was all the way into the beginning of the year.  Bot?  Perhaps.  Inexcusably SLOPPY, even for proprietary software practices?  YEP. 

PLEASE, folks don't just excuse what is something the Courts (because you're required to do due dilligence on things like, "bots," doing this) would deem as a WILLFUL ACT OF INFRINGEMENT.  If the shoe were on the other foot, you'd have hoards of lawyers descending upon you before you could even remotely sort it out...if you even could.

**Comment by jeffwilcox** [comment]
We've reverted the incorrect LICENSE files in the repository and are going to look through the other forks where this may have happened. I wrote the bot code that's misbehaving and feel horrible about this.

**Comment by madscientist42** [comment]
You had this lurking for almost a year...not really acceptable enough to say, "sorry" by and of itself.

**Comment by madscientist42** [comment]
If Microsoft had that happen to THEM...do you think they'd just say, "It's all okay...it's fixed now"?

**Comment by CarlSchwan** [comment]
Thanks for the update @jeffwilcox

**Comment by cnmade** [comment]
你们所有开源作者，应该 向微软道歉，你们侵犯了微软的权利，你们在开源代码的同时，居然胆敢写上自己版权所有？还得麻烦微软亲自帮你们一一改正过来。
给你们一天时间，快自己主动改成微软。
所有github项目，版权归微软所有。
烦请所有开源项目，早日改邪归正，不要迷途不返。

**Comment by dmccollough1** [comment]
> You had this lurking for almost a year...not really acceptable enough to say, "sorry" by and of itself.

Exactly this. Do proper code and repo reviews.

**Comment by michaelrsweet** [comment]
OK, folks, I think this discussion has reached a natural conclusion. FWIW, as the original author of all this code *I* am not offended and am happy that things have been fixed in the MS forks.
