### ISSUE TITLE
CUPS inside Docker Container - can't find my Printer

### ISSUE THREAD

**Issue by Bennneeeet** [OpenPrinting/cups#324]
Hello 👋 

i've installed CUPS 2.2.10 on my Raspberry Pi 4 inside a docker container.
On the IP (192.168.178.55 Port 80) is also running a Nextcloud installation (if it's important to mention).

I configured CUPS on Port 631 and added successfully my printer. Tried to print a test page - it worked!

But I can't see that printer in my network (Yes, I've checked that share printer checkbox).
So I'm not able to print from another computer over the network. 

What could be the problem? Or better: what could be the solution?
I can imagine that something isn't connect right between host and docker container.

Docker container:
````
0be0726f182d  |  lemariva/rpi-cups |  "/usr/sbin/cupsd -f"  |   0.0.0.0:631->631/tcp, :::631->631/tcp
````

I used the following to build the container:
````
sudo docker run -d --restart unless-stopped -p 631:631 --privileged -v /var/run/dbus:/var/run/dbus -v /dev/bus/usb:/dev/bus/usb lemariva/rpi-cups
````

===
Long time ago I installed CUPS directly (without docker) on my Raspberry Pi 3 and there was everything fine.

**Comment by zdohnal** [comment]
Hi @Bennneeeet ,

print queue sharing in CUPS happens via mDNS (since long time ago, approx CUPS 1.5 or so), so for the other machines to see your shared queue you need to have:

- Avahi running in your docker image for CUPS to be able to register printer there
- mDNS communication has to allowed from the image
- the client machines have to accept mDNS communication and have Avahi running for CUPS to be able to discover the shared queue and offer it to you in print dialog without installation (if the dialog supports it... applications based on newer GTK+ - approx 3.25.24 or newer - or Libreoffice can do it)

Note: In case your dialog doesn't support this CUPS feature called a temporary queue, you can try starting cups-browsed or installing the printer manually (I'm not quite sure how URI from docker image would look like - without docker in play the uri would look ```ipp://<hostname/IP>:631/printers/<queue_name>```).
