### ISSUE TITLE
Wrong copyright info on some pages

### ISSUE THREAD

**Issue by Rishabh-792** [OpenPrinting/cups#346]
Currently, the home page footer shows the copyright for OpenPrinting, but on other pages, it shows the copyright for Apple Inc.

Attaching the screenshots for this : 
![WhatsApp Image 2022-03-02 at 5 33 30 PM](https://user-images.githubusercontent.com/79650357/156608096-9c88b28e-aa51-4586-bbaa-922bdab01737.jpeg)
![WhatsApp Image 2022-03-02 at 5 33 30 PM (1)](https://user-images.githubusercontent.com/79650357/156608121-8eacfddd-c184-449b-85e3-a71536cad005.jpeg)

Is this a bug ?
If yes, then I can try to create a PR for fixing this :)

**Comment by zdohnal** [comment]
Hi @Rishabh-792 ,

thank you for reporting the issue!

The code copyright can be changed due license, but I'm not quite sure (since IANAL) about the logo - @michaelrsweet , do you know if the open source license can be applied to logos? Like since we forked the project under Apache License 2.0 with CUPS exceptions, is the logo under OpenPrinting, or is it still Apple?

**Comment by michaelrsweet** [comment]
@zdohnal The OpenPrinting CUPS logo is a new design by me, and yes as a creative work it can be copyrighted just like code, text, etc. The footer should be consistent for all pages and languages, specifically pointing to OpenPrinting.

**Comment by Rishabh-792** [comment]
@zdohnal @michaelrsweet Created a PR #349 for fixing this.
