### ISSUE TITLE
RHEL 8 client to Win 2019 PS

### ISSUE THREAD

**Issue by ggrundstrom** [OpenPrinting/cups#350]
I have a remote Windows Server 2019 Print Server hosting an HP and a Zebra printer. I'm using a RHEL 8 server with CUPS 2.2.6 as the client trying to connect and print to Windows PS printers. I have all firewall blocks resolved since if I replace the RHEL 8 server with a Windows server I can print successfully.
I have issued ipptool -tIv http://Win PS IP Address:80/printers/HP_LaserJet_Pro_M404-M405/.printer get-printer-attributes.test. It immediately returns with:
Get printer attributes using Get-Printer-Attributes [FAIL]
RECEIVED: 0 bytes in response
status-code = server-error-internal-error (No request sent.)
IPP request failed with status server-error-internal-error (No request sent.)

Nothing obvious I see in logs.  Is there a way to get more descriptive info from the status-code above?

I've tried the default cupsd.conf and also adding in various directives such as BrowseRemoteProtocols, BrowsePoll, BrowsePort, and others.  All print jobs in CUPS attempt to print, then errors with "Filter Failed" status.  Most posts I've found are using Linux as the print server and trying to connect Windows as the client. My use case is the opposite with Windows as the PS and Linux as client, so not much help.  Is this config supported?  If so, what have others done to make it work?

**Comment by zdohnal** [comment]
Hi @ggrundstrom ,

thank you for reporting the issue!

If you have an active RHEL 8 subscription, please report the issue to https://access.redhat.com - support engineers will help you there.

Ad ipptool - the tool is used for sending an IPP request to the device uri you've provided as a parameter - the Win Server must support IPP and have port 631 opened to make it work. Additionally, the device uri to the print queue must be correct. I'm not sure how the uri looks on Win Server, but RHEL 8 can work with a following uri:

```
$ ipptool -tv http://<hostname or IP>:631/printers/BRQ-TPBC-1D124-North get-printer-attributes.test
```

Connection can be even ```http``` in RHEL 8 (since it is a symlink to ipp), but then the port must specified (:631).

Ad Linux client -> Win Server connection - AFAIK in CUPS 2.2.6 the queue installation and printing is possible only via Samba. The current CUPS - 2.4.1 - has OAuth support, so it can support Windows Internet Printing Service, but CUPS 2.2.6 doesn't have the support.

In any case, please contact your support at https://access.redhat.com , they can help you out further.
