### ISSUE TITLE
driverless, cups-filters 1.28.7 error

### ISSUE THREAD

**Issue by Scotsgeek** [OpenPrinting/cups#366]
This is a followup to closed issue #359:

On Debian Linux, using command, "lp -o sides=two-sided-long-edge filename.pdf"

Using "HP LaserJet Pro M148f-M149f, driverless, cups-filters 1.28.7" it will NOT print two-sided, and tends to jam up the print queue. I sometime have to force the print job in the queue.

Using "HP LaserJet Pro M148-M149 Postscript (recommended)", it does print two-sided, and does not jam the print queue.

Please look at the "Driverless cups-filters"

Thank you!

**Comment by zdohnal** [comment]
Hi,

from the last findings, there is a firmware bug in your printer's IPP implementation. Unless that is fixed in firmware, you won't be able to print two-sided via driverless driver. The same as you wasn't able to print via queue which was created by cups-browsed.

However, the jamming the queue should not happen - would you mind providing the following information:

-turning on CUPS debug logging, reproducing the issue, getting the file /var/log/cups/error_log, adding .txt suffix to it and attaching it here?
- attaching your ppd file from /etc/cups/ppd with .txt suffix to this issue.
- get the result of get-printer-attributes request from ```ipptool -tv <device_uri> get-printer-attributes.test``` and attach them here as a file with .txt suffix.

The driverless driver is part of cups-filters, but I would like to gather all necessary information before passing over the issue.

Thank you in advance!

**Comment by Scotsgeek** [comment]
I am in the process of replacing my computer.  Let me complete that process, run tests, then I will respond.  Thank you!

**Comment by Scotsgeek** [comment]
My old computer was Debian Bullseye, version 11, fresh installed O/S, where I reported the problem.  Perhaps leftover settings in my /home partition which was not recreated.  Not sure.

My new computer is Debian Testing, and before installing cups-pdf, and after, lp & lpr worked correctly.  Freshly installed a new /home partition, and only brought over essential directories and settings.

I do not have a spare computer to fully install a fresh Debian Stable to test.

Thanks for your time.

**Comment by zdohnal** [comment]
Thank you for the info!
