### ISSUE TITLE
Enhancement: Add shared library support for AIX

### ISSUE THREAD

**Issue by aixtools** [OpenPrinting/cups#389]
I am aware the AIX is not an officially supported platform - but the core change needed to support it is quite small - and updated DSOFLAGS and supporting LDFLAGS.

Would be great to have the basic support for AIX back in play.

While I, personally, prefer having shared library support in (fat) archives - having the SYSV support of `\.so` files is a great step forward.

Will submit a PR asap.

**Comment by aixtools** [comment]
FYI: The PR #390 has been tested on AIX 5.3 TL7 (for build) and AIX 7.1 (used in OSS project requiring CUPS support). Compiler is xlC-v11.

**Comment by michaelrsweet** [comment]
@aixtools If you are willing to take on the responsibility of periodically testing and submitting PRs to keep CUPS building on AIX, I can move AIX from the "unsupported" list to the "supported by their developers" (middle tier) list. The only reason why AIX support was dropped was because the last time *I* had an AIX system was 15 years ago and there were no other developers/resources available to continue it.

**Comment by StefCoene** [comment]
Hi,

If you need an extra tester for AIX, you can contact me.
Currently, there is an issue with the CUPS on AIX but I will open a new issue for it.


Stef
