### ISSUE TITLE
Forward over SSH.

### ISSUE THREAD

**Issue by stefbon** [OpenPrinting/cups#441]
Hello,

I'm working on a set of tools to enable sharing files, communicate and work better together in a office environment. My main platform is Linux, for workstation and server. To do so I've written a SSH library, a SFTP library and FUSE library to provide users a browseable map to access available shared directories via SFTP.  (using Avahi to detect services in local network for now).

See:

https://osns.net/
https://github.com/stefbon/OSNS

Next to filesharing I want to add:
- chat over ssh (text and/or video) in groups or one to one.
- remote desktop using existing Arctica
- a common clipboard on the network

Todo are a CA (providing certificates), an identity database like OpenLDAP, caching of identities to the users session using a user namespace and local OpenLDAP server and central ACL's.

I also want to make printerspoolers available, let the OSNS suite find the available printer spoolers, and create a local socket, so client programs do not have to do this. and integrate the sharing of printers in the whole setup (have users rights? etc).
I'm looking fro the best way to do this. I see that cups can listen to a TCP socket and a local/Unix socket. SSH provides for both socket domains/families ways to forward/connect the client to the servers socket. I've been looking for documentation about the local socket, but I cannot find any. (also not in manpages of lp and relatives and dco on the website). Or is the best way TCP ?

Thanks in advance,
Stef Bon
the Netherlands

**Comment by zdohnal** [comment]
Hi Stef,

AFAIK CUPS uses a classic unix domain socket, so it doesn't have any special documentation about it.

IIUC what you want to do, you will have to have both, in case you don't want to go through TCP socket all the way. For communication with applications on local machine, unix domain socket is preferred. But since you want to share the printers, you will need TCP socket for other machines in network to connect to your SW.

**Comment by stefbon** [comment]
Hi,

so - correct me if I'm wrong - all cups aware programs will try to connect to the local socket first, and then the TCP 127.0..0.1:631 address?
I prefer the unix socket, you can check the access beter (uid/gid of peer are available).

Stef

**Comment by michaelrsweet** [comment]
@zdonal I think @stefbon was asking how to direct clients to an SSH tunnel, and how to maybe do this automatically.

The `CUPS_SERVER` environment variable and `client.conf` file can direct the client software to a different server. The web interface won't work and there will be limitations for localization, etc. since the mapped host and port doesn't match what SSH is talking to...

**Comment by stefbon** [comment]
Aha. I was looking for such a environment variable. I can remember CUPS_SOCKET, but maybe I'm mistaken.

I know the clients connecting to the local to be forwarded socket to the server maybe misleading to clients since the host offering the socket (localhost) is another than the printers are connected to. I see how to handle these issues when I start to implement that.

Thanks,

Stef Bon

**Comment by zdohnal** [comment]
> Aha. I was looking for such a environment variable. I can remember CUPS_SOCKET, but maybe I'm mistaken.

Or you can use ```cupsSetServer()``` in application which needs to communicate a different target then the local cupsd - every other CUPS API functions since then will send the request to the destination defined by ```cupsSetServer()```.

> 
> I know the clients connecting to the local to be forwarded socket to the server maybe misleading to clients since the host offering the socket (localhost) is another than the printers are connected to (the server with cups). I hope I can handle these issues when I start to implement that.

Yep, this confusing behavior can lead into spamming the remote server with 'invalid' requests, if user/daemon on local machine thinks it is talking with local cupsd, where it has permissions to add or modify printers, but in reality it talks with remote cupsd, where the local user doesn't have such permissions.

> 
> Thanks,
> 
> Stef Bon

Does @michaelrsweet reply answer your question? Can I close the issue?

**Comment by zdohnal** [comment]
In case there are more question, feel free to ask. Closing this for now.
