### ISSUE TITLE
cups.path: Failed with result 'unit-start-limit-hit'

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [OpenPrinting/cups#467]
```
PS /home/BEEDELLROKEJULIANLOCKHART> systemctl --failed                             
  UNIT      LOAD   ACTIVE SUB    DESCRIPTION   
● cups.path loaded failed failed CUPS Scheduler

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
PS /home/BEEDELLROKEJULIANLOCKHART> systemctl status cups.path   
× cups.path - CUPS Scheduler
     Loaded: loaded (/usr/lib/systemd/system/cups.path; enabled; vendor preset: enabled)
     Active: failed (Result: unit-start-limit-hit) since Thu 2022-09-01 10:49:33 BST; 25min ago
   Triggers: ● cups.service

Sep 01 10:49:33 BEEDELLROKEJULIANLOCKHART.1660221716 systemd[1]: Started cups.path - CUPS Scheduler.
Sep 01 10:49:33 BEEDELLROKEJULIANLOCKHART.1660221716 systemd[1]: cups.path: Failed with result 'unit-start-limit-hit'.
```
```
PS /home/BEEDELLROKEJULIANLOCKHART> dnf info cups
Last metadata expiration check: 0:01:13 ago on Thu Sep  1 11:15:55 2022.
Installed Packages
Name         : cups
Epoch        : 1
Version      : 2.4.2
Release      : 4.fc36
Architecture : x86_64
Size         : 8.1 M
Source       : cups-2.4.2-4.fc36.src.rpm
Repository   : @System
From repo    : updates
Summary      : CUPS printing system
URL          : https://openprinting.github.io/cups/
```

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@zdohnal, I do not know what caused this.

**Comment by rokejulianlockhart** [comment]
@zdohnal,

https://github.com/OpenPrinting/cups/issues/467#issuecomment-1234276293

> It would be great if you provided steps how to reproduce the issue, it helps with investigation.

https://bugs.kde.org/show_bug.cgi?id=454409#c0

<blockquote>

- What I was doing when the application crashed:
I have been able to scan 2 times, but currently Skanlite is unable to preview and reselect the device. I have not interacted with my printer since my 2nd initialisation of Skanlite. This error occured during my 3rd and subsequent initialisations.

- Custom settings of the application:
This occurred during my 3rd initialisation of Skanlite. The previous initialisation did not retain what I configured during my 1st initialisation. The 3rd initialisation retained the configuration of the 2nd initialisation.

Closure of Skanlite and subsequent disablement and enablement of my scanner has remediated this problem: I was instructed to choose the device to utilise, I am able to preview and scan, and Skanlite did not retain my previous configuration.

The crash can be reproduced every time.

**Comment by zdohnal** [comment]
Ok, IMO the reason for this is that cups.path tried to start cups.service several times in small time frame, but the service always failed. I would say we could see more information in cups.service logs, but since you don't use the system anymore, there's not much to do.
