### ISSUE TITLE
Contribute CUPS Filter Driver for BIXOLON Label Printers

### ISSUE THREAD

**Issue by sahayap** [OpenPrinting/cups#490]
Hello Team,
I am Sahaya Darcius, working as a R&D engineer at BIXOLON CO Ltd, in South Korea, We are leading POS printer manufacturing company and providing CUPS based printing solution to our customers, Now we want to submit our CUPS filter and PPD files to CUPS library, which is good for our customers, this is also the request of many of our customers.

What are the procedure to submit our CUPS filter and PPD files,

Please guide.
Thank you.
Sahaya P

**Comment by michaelrsweet** [comment]
@sahayap We don't generally include vendor drivers in CUPS itself, and in particular we are in the middle of a years-long migration *away* from printer drivers and towards IPP/IPP-USB supporting printers and (for legacy devices that cannot support IPP or IPP-USB) *printer applications* that encapsulate the driver behind an IPP shim layer, typically based on [PAPPL](https://www.msweet.org/pappl).

In the case of label/receipt printers, my [LPrint](https://www.msweet.org/lprint) printer application is becoming the project to host these drivers, so I recommend you look at porting and contributing what you have to that project. I'll need a sample printer to test with, but am happy to incorporate your driver there.

**Comment by sahayap** [comment]
Dear Michael R Sweet,
    Thank you so very much for your prompt reply.
Our current label printer driver is a raster filter driver, based on CUPS filters. 

If we want to port it to [LPrint](https://www.msweet.org/lprint), can we port it without changing our driver source?  Or write a new driver based on [LPrint](https://www.msweet.org/lprint)? Please send me a sample driver for reference.

Thank you

With Regards,
Sahaya P

**Comment by michaelrsweet** [comment]
@sahayap You can look at the existing LPrint drivers - basically they split out the code from rastertolabel and incorporate what used to be done via PPD/drv files as in-memory data structures. There is a [tutorial](https://www.msweet.org/pappl/pappl.html#the-hp-printer-application-example) included with PAPPL that explains how to do the conversion (hp-printer-app is a conversion of the rastertohp driver, LPrint is a conversion of the rastertolabel driver) and I can help you with the last bits to integrate into LPrint since it adds a second layer to PAPPL to support multiple label printer drivers within a single printer application.

**Comment by zdohnal** [comment]
Hi @sahayap ,

thank you for being willing to share your driver into open source printing stack! Since as Mike mentioned any future work will happen in LPrint, I'm going to close this issue.

I've created a new issue at Lprint project to track this - https://github.com/michaelrsweet/lprint/issues/78 .

**Comment by sahayap** [comment]
Dear @michaelrsweet 
 Thank you for the response,
If we go for LPrint based, we have to develop our driver again, it is a time consuming process.  
Since our driver is based on CUPS filters,  can't we just integrate our filter driver into rastertolabel source code and send the DIFF and PPD files, is it not enough to support our driver by CUPS? its a easy and faster way to include our printers supported by CUPS. 

Please clear me.

Thank you
With Regards,
Sahaya P

**Comment by michaelrsweet** [comment]
@sahayap The CUPS rastertolabel driver is *deprecated*, and adding it now will only delay the inevitable need to port to LPrint (or another printer application) by a couple years. We have been moving towards this point for over 10 years now...

**Comment by sahayap** [comment]
Dear @michaelrsweet 
Thank you for the details. 
we will do internal review and will get back to you for further process.

With Regards,
Sahaya P
