### ISSUE TITLE
Default media source not working

### ISSUE THREAD

**Issue by UK011** [OpenPrinting/cups#497]
We have setup printserver OpenPrinting CUPS 2.4.1
Installed printer Kyocera TASKalfa 306CI (IPP Everywhere) and configured default tray 2 (media source 2), but its still prints from the first tray. 
Any idea in which direction to check and fix this?

**Comment by zdohnal** [comment]
Hi @UK011 ,

thank you for reporting the issue!

It would be great if you shared output of ```lpoptions -p <printer> -l```, turned CUPS debug logging by ```cupsctl LogLevel=debug2```, tried to print with default tray 2 set and attached ```/var/log/cups/error_log``` with .txt suffix here after reproducing the issue.

It is possible your application sends PPD option for the first tray, overwriting your default, but I have to check the logs first.

**Comment by UK011** [comment]
[error_log.txt](https://github.com/OpenPrinting/cups/files/9830794/error_log.txt)

**Comment by tillkamppeter** [comment]
> I see the job 216 having `output-bin=face-down OutputBin=FaceDown`, so it would be great if we knew what options the printer has.

@zdohnal, note that this is about input trays, not output trays ...

**Comment by yuvraj-aseri** [comment]
Hii @UK011 ,
Could you please post your `/var/log/cups/error_log` and Printer's ppd `/etc/cups/ppd/` file after a job with the problem?  Set CUPS to debug logging before sending the job (`cupsctl --debug-logging`) and when attaching your error_log after the job, rename the file to have a `.txt` extension so that GitHub accepts it.
