### ISSUE TITLE
Unable to add printer Ricoh with IPP-over-USB

### ISSUE THREAD

**Issue by bfg01** [OpenPrinting/cups#502]
Printer is Ricoh SP 377SFNwx. Using openSUSE Leap 15.4, installed from scratch (no upgrade).

As network printer, with URI ipp:// and driver "everywhere", seemingly no problems until now.

Wanted to try with IPP-over-USB.
So connected printer via USB, and tried "lpinfo -v". There was this found URI "direct usb://UNKNOWN/Printer[...]".
Did internet search and found that an additional daemon was needed: https://github.com/OpenPrinting/ipp-usb
So manually downloaded the RPM package and installed.
Now shown URI was "direct usb://RICOH/SP[...]" (cannot remember it exactly)

So tried adding it, and got:
```
# lpadmin -p <a_name> -Ev usb://RICOH/SP[...] -m everywhere; echo $?
lpadmin: Unable to connect to "RICOH:0": Name or service not known
1
```

Tried several things:
---Double-checking that firewalld was -temporarily- disabled (otherwise "lpinfo -v" wouldn't even have worked)
---Trying URI ipp://RICOH/SP[...] instead
---Trying the "lsusb" advice here https://wiki.debian.org/CUPSDriverlessPrinting#IPP-over-USB:_The_Basics ; and I did get the right output like there says, so printer does have support for this

Could someone help please?
Thanks for your attention.

**Comment by michaelrsweet** [comment]
"usb://..." URIs are *not* IPP-USB, but the old/legacy USB printer class interface. You can't actually use IPP Everywhere with it over legacy USB.

Some network MFPs do not support IPP-USB since the USB port is treated as a "maintenance" port. But if the printer *does* support IPP-USB then "lpinfo -v" should show it with an "ipp:" or "dnssd:" URI.

**Comment by bfg01** [comment]
Thanks very much sir.

Well, "lpinfo -v" *does* show the printer with "ipp://..." and "dnssd://...", but as far as I have understood in the CUPS docs, these are purely network protocols; i.e., only usable through network connection (ethernet or wifi).
In fact, as mentioned in the OP, I already added it as a network printer.

The only other URIs shown by "lpinfo -v" are "socket://..." and "usb://..." itself.

I'm not at office right now, but I thought about a weird idea: trying to isolate both PC and printer, connect with USB, and use "ipp://..." URI to see if it's detected. But AFAIK, the *only* IPP URIs shown by "lpinfo -v" even when USB connected were "ipp://<ip_address>" and "ipp://<model_name_with_strange_format>"...
Am I just completely wrong regarding IPP-USB? Is there still a way to test IPP-USB with this printer?

Thanks again for your help.

**Comment by michaelrsweet** [comment]
So IPP-USB shows up as a network protocol because the ipp-usb daemon provides a gateway from localhost (127.0.0.1 or ::1)  to the IPP-USB endpoints provided by the printer.

**Comment by zdohnal** [comment]
@bfg01 it is as @michaelrsweet says - the ipp-over-usb device works via network ipp backend, because they're shared on localhost by ipp-usb daemon as an IPP printer. However, you can always deduct whether the device is actually USB by checking the mDNS record ipp-usb shares, f.e. ```avahi-browse -avrt``` output:

```
=     lo IPv4 Canon MF440 Series (USB 1)                    _ipp._tcp            local
                                                       ^^^^^
   hostname = [fedora.local]
   address = [127.0.0.1]
   port = [60000]
   txt = ["air=none" "mopria-certified=1.3" "rp=ipp/print" "priority=50" "kind=document,envelope,postcard" "PaperMax=legal-A4" "URF=CP255,DM1,PQ4,RS300,W8-16,FN3,IS1-4,OB10-40,V1.4" "UUID=6d4ff0ce-6b11-11d8-8020-00bbc1796a37" "Color=F" "Duplex=T" "note=" "qtotal=1" "usb_MDL=MF440 Series UFR II" "usb_MFG=Canon" "usb_CMD=LIPSLX,CPCA" "ty=CNMF440 Series" "product=(CNMF440 Series)" "pdl=application/octet-stream,image/urf,image/pwg-raster,image/jpeg,application/pdf" "txtvers=1" "adminurl=http://localhost:60000/airprint.html" "Fax=F" "Scan=T"]
```

Ad testing:

First it would be great if you found out whether the device really supports ipp-over-usb protocol. There is an easy way how to find out via ```lsusb -v``` - you look for your device entry and the following lines:

My device entry:

```
Bus 001 Device 005: ID 04a9:2823 Canon, Inc. MF440 Series
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.10
...
```

and further down in the entry I can see it has an interface 7/1/4, which is ipp-over-usb interface:

```
...
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      4 
      iInterface              0
...
``` 
If your device does not have the similar ```lsusb -v``` output, the device doesn't support ipp-over-usb.

If you verified the device really is ipp-over-usb, then you can test the device in two ways:

A) via temporary queue - this requires the OS which is capable of using mDNS (having nss-mdns or systemd-resolved and set up installed for mDNS resolving, running avahi-daemon) and the application capable of using the current (6 years old) CUPS API - AFAIK this works in Fedora and Ubuntu (Ubuntu achieves this by running cups-browsed natively), I'm not sure about OpenSUSE. Applications capable of using CUPS API are at least Firefox, Libreoffice and any GTK3 based application. Temporary queues will be one of the ways how to use printers in the future CUPS, so I strongly recommend trying this one.

B) via a permanent queue - you can add the queue permanently by using this command:

```
$ lpadmin -p <name> -v ipp://localhost:60000/ipp/print -m everywhere -E
```
This way will no longer be available for common printing in the future CUPS - it will be used only for sharing the queue on the CUPS sharing server - but today you can try this way to figure out whether your device works via ipp-usb as well.

======================

Note: there is ```driverless``` backend from cups-filters, which can show your ipp-usb device in ```lpinfo -v``` like this:

```
ipp://Canon%20MF440%20Series%20(USB%201)._ipp._tcp.local/
```

but there is an issue which results this discovery is not reliable - the uri is shown sometimes, but then it is not... so that's why, if you have to try a permanent queue, I recommend using ```localhost:60000/ipp/print``` in uri instead.

**Comment by zdohnal** [comment]
And ipp-usb has its own logs - consult with its man pages how to enable debug logging and where to find the logs.

Closing the issue for now, do let me know the result and we can find out whether there is a problem we can solve in CUPS.

**Comment by bfg01** [comment]
Isolated both printer and PC from any network, started IPP USB daemon with "ipp-usb debug", then connected each other via USB cable.

I already did the "lsusb -v" test, as mentioned in the OP with "the Debian link", and I still get the output.

Tried the temporary queue, both with LibreOffice and "lpstat -l -e". No URIs found at all...

Tried adding permanent queue; result: "lpadmin: Error [...]: Operation now in progress".
And I did temporarily disable firewalld

Both "driverless [list]" and "lpinfo -v" show no URIs, except the legacy "usb://..."
