### ISSUE TITLE
Unable to add the ipp network printer to cup server 

### ISSUE THREAD

**Issue by Krishnanudhaya** [OpenPrinting/cups#514]
Hi Team,

I would like to add the network printer to cups server using http call ( printer_host_name, port).

I couldn't find the way to add the printer to cupserver from cups api documentation.

Please share the cup api which allows to add ipp network printer into cups and share the different approaches to connect the printer.

Currently, I have connecting the cup server with cups4j library through java.

Thanks and Regards,
Krishnan
India

**Comment by michaelrsweet** [comment]
See the [CUPS Implementation of IPP](https://openprinting.github.io/cups/doc/spec-ipp.html), specifically the information about the [CUPS-Add-Modify-Printer](https://openprinting.github.io/cups/doc/spec-ipp.html#CUPS_ADD_MODIFY_PRINTER) operation. The "ppd-name" attribute will have a value of 'everywhere' for an IPP Everywhere printer, otherwise you need to specify a driver/model name (`lpinfo -m`) corresponding to the printer.

For a C code example, look at the "lpadmin.c" file in the CUPS source code.

**Comment by Krishnanudhaya** [comment]
Thank you for the response.

**Comment by michaelrsweet** [comment]
@gmuth macOS uses an old version of CUPS that doesn't support the "everywhere" virtual PPD; instead, the "lpadmin" command and "admin.cgi" programs did the PPD generation and provided the PPD file as an attachment.

**Comment by michaelrsweet** [comment]
@gmuth It can be anything, including /dev/null - IIRC it is used to update a print queue.
