### ISSUE TITLE
Cannot disable TLS in DNS-SD announcments

### ISSUE THREAD

**Issue by miegl** [OpenPrinting/cups#524]
When announcing shared printers via mDNS with:
```
Browsing On
BrowseLocalProtocols dnssd
```

CUPS announces shared printers with TLS  enabled:
```
=   wlo1 IPv4 HP_LaserJet_P1005 @ a                      Internet Printer     local
   hostname = [a.local]
   address = [172.16.0.1]
   port = [631]
   txt = ["printer-type=0x80901E" "printer-state=3" "Duplex=T" "Color=T" "TLS=1.2" "UUID=cbc87b0d-2476-3972-7ee4-85aede3cb561" "pdl=application/octet-stream,application/pdf,application/postscript,image/jpeg,image/png,image/pwg-raster" "product=(HP LaserJet p1005 Printer)" "priority=0" "note=" "adminurl=https://a.local.:631/printers/HP_LaserJet_P1005" "ty=HP LaserJet p1005, hpcups 3.22.10, requires proprietary plugin" "rp=printers/HP_LaserJet_P1005" "qtotal=1" "txtvers=1"]
```

However, devices on my local network (Linux CUPS, Windows 10) fail to print using IPPS, maybe due to the self-signed certificate? When changing the printer queues to use the `ipp://` scheme instead of `ipps://`, printing works. (When using CUPS, I get `Backend returned status 4 (stop printer)` without even connecting to the remote CUPS server.)

I tried to disable TLS with options like:
```
DefaultEncryption Never
Encryption Never
```
but to no luck.

What are my options? I'm not really sure how to get CA-signed certificate for mDNS, so I'm looking to disable TLS in these announcements all together.

**Comment by skbeh** [comment]
I also want a feature that allows me to disable the advertisement of only ipp or ipps.

**Comment by michaelrsweet** [comment]
This might be related to #529 - try adding the following to your cups-files.conf file on the server and restart cupsd:

```
ServerKeychain ssl
```

**Comment by skbeh** [comment]
@michaelrsweet I use Arch Linux which links cups to gnutls.

**Comment by michaelrsweet** [comment]
@skbeh The original reporter was complaining that IPPS wasn't working due to certificate issues. Your wanting a non-TLS advertisement is a separate issue and should be filed separately...

**Comment by skbeh** [comment]
@michaelrsweet Sorry, I missed that.

**Comment by miegl** [comment]
> This might be related to #529 - try adding the following to your cups-files.conf file on the server and restart cupsd:
> 
> ```
> ServerKeychain ssl
> ```

Thank you, this has worked.

**Comment by madsl** [comment]
Can we reopen this issue again?

After extensive testing in Windows 11 24H2 with cups 2.4.11, it does not support adding printers with TLS=1.2 enabled when shared through DNS-SD, even if you share it from a CUPS instance with valid SSL certificated, and CA added to the Windows certificate store (so https://cups-server:631 is valid inside of Windows).

But, if you manually recreate the printer service in Avahi, but omit <txt-record>TLS=1.2</txt-record> and make sure that admin-url is with http, adding printers just through the "Add" button in Windows works great.

I suspect the reason is a bug in Windows (because manually adding printers with an https url does not work either, but http does), but that still makes it necessary to support sharing printers through DNS-SD without TLS.

**Comment by michaelrsweet** [comment]
@madsl I don't think the TLS stuff is the problem.

With respect, the "https" URI scheme is *not valid* for IPP. I know Microsoft continues to use this for their Universal Print stuff, but the http/https URI schemes have not be valid since IPP/1.1 was published 26 years ago and CUPS will reject any request that attempts to use a printer URI with "http" or "https" (and thus prevent you from adding the printer).

That said, I *do* know that the Microsoft IPP class driver works with modern IPP printers discovered via mDNS/DNS-SD and is able to send ipp or ipps URIs, regardless of the presence of the TLS key. When I add a printer on my Win11 laptop I see the printer shared by my local CUPS server and am able to add it successfully and print a test page, so that *seems* to be working. The only "odd" thing I see on my CUPS server is that Windows isn't using the mDNS hostname of the CUPS server but rather an IPv6 address...

**Comment by madsl** [comment]
@michaelrsweet  I'm not sure what you're arguing here...

No matter what your stance is on what the error actually is - is your point that CUPS shared printers should always have TLS=1.2 when published over DNS-SD no matter what?

It's an extreme hassle to add your own CA to Windows just to be able to use a TLS connected printer. Surely this should be a thing that is togglable in a configuration option somewhere so you don't have to do this?

**Comment by michaelrsweet** [comment]
@madsl 

> No matter what your stance is on what the error actually is - is your point that CUPS shared printers should always have TLS=1.2 when published over DNS-SD no matter what?

Yes.

The TLS key advertises the maximum version of TLS supported by the service. TLS upgrade is a thing for IPP and is required by the standard if you support TLS/IPPS...

> It's an extreme hassle to add your own CA to Windows just to be able to use a TLS connected printer. Surely this should be a thing that is togglable in a configuration option somewhere so you don't have to do this?

You can absolutely compile CUPS 2.4 and earlier without TLS support, which will remove the TLS key. But that will cripple any security/confidentiality for printing through that CUPS server, regardless of the Client OS.

Unless you have a specific security policy enabled on your Windows clients, they absolutely should allow encrypted (IPPS) printing with the normal self-signed certificates managed by CUPS, since that is the current "state of the art" for printers. The self-signed certificates are "pinned" to the queues during setup.

Beyond that I have been pushing for support of local ACME CAs in order to allow printers, servers, and other IoT devices to get trusted certificates for several years. The alternative in your case would be to have a MS certificate server client that could provide the certificate for the CUPS server, allowing Windows clients to accept the certificate used for TLS without additional configuration on the client side.

Regardless, the problem is NOT that CUPS is correctly advertising its TLS support.

**Comment by madsl** [comment]
Here's hoping more people test this out, because in my experience the only way to get automatic adding in Windows to work (to reiterate, the "add printer" button in Settings, not going through the printer wizard, that has always worked) to work is to publish the printer without TLS=1.2, even with proper certificates.

**Comment by michaelrsweet** [comment]
@madsl Sadly, the "add printer manually" stuff is horribly broken in Win10+ for basically everything.
