### ISSUE TITLE
cups may need systemd network-online.target instead of network.target

### ISSUE THREAD

**Issue by andyrtr** [OpenPrinting/cups#53]
I'm not sure what the current policy of duplicate entries to the apple/cups issus is but for discussion I reopen a duplicate of https://github.com/apple/cups/issues/5709 here as well also to discuss if more Linux distributions are affected.

Running Arch Linux with cups built from the OpenPrinting/Cups fork of todays master I still can't reach my network cups server using its webinterface and it doesn't offer the printer to the network after fresh reboot. A "systemctl status cups" shows it active and properly started though. A manual systemd restart cups.service solves it. My local solution using in Arch Linux is to further modify the service file

```
--- cups-2.3.0/scheduler/cups.service.in        2019-08-23 17:19:38.000000000 +0200
+++ cups-2.3.0/scheduler/cups.service.in.new    2019-08-25 20:20:25.805339727 +0200
@@ -1,8 +1,9 @@
 [Unit]
 Description=CUPS Scheduler
 Documentation=man:cupsd(8)
-After=network.target sssd.service ypbind.service
+After=network-online.target sssd.service ypbind.service
 Requires=cups.socket
+Wants=network-online.target

 [Service]
 ExecStart=@sbindir@/cupsd -l
```

Acording to https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/ this shouldn't need be needed and I'd prefer to find out why network.target isn't enough to make cups properly working here.

Attaching here a cups debug [error_log.txt](https://github.com/OpenPrinting/cups/files/5603724/error_log.txt) using network.target make the start failing and the working
[error_log_working.txt](https://github.com/OpenPrinting/cups/files/5603766/error_log_working.txt)

Maybe you have an idea why network.target isn't working for me while it does seem to do so in different distributions.

**Comment by zdohnal** [comment]
Hi @andyrtr ,

from a brief look in logs you use a remote access (you connects to 192.168.1.90 and there is a message - 'Remote access is enabled.')- which means you have cupsd set to connect to cupsd on remote machine. It is set probably via ```ServerName```/```ServerAlias``` directives in ```/etc/cups/client.conf``` or ```/etc/cups/cupsd.conf```.
And based on ```network.target``` and ```network-online.target``` definition - the former indicates only network management stack is up. Cupsd usually listens on ```localhost:631``` so it needs only port 631 to be prepared, so ```network.target``` suffices.
On the other hand, since you enabled a remote access, you need to have a network really working. The definition of 'working network' here is based on network management software (f.e. NetworkManager), so ```network-online.target``` is reached when this specific software is started and it configured the network (mostly by assigning IP).

Putting ```network-online.target``` into ```cups.service``` by default would delay startup (especially when you aren't in any network), so I wouldn't advice to make it default for all.

However, if you really need the remote access and cupsd working this way, you can create ```/etc/systemd/system/cups.service.d/<name>.conf``` drop-in with:

```
[Unit]
After=network-online.target
Wants=network-online.target
```

and then do ```systemctl daemon-reload```. You can check the result via ```systemctl cat cups```.

**Comment by andyrtr** [comment]
The remote system with cupsd running has IP 192.168.1.90 and is setup with 
`Listen 192.168.1.90:631` and `Allow 192.168.1.*` in Location directivities in `cupsd.conf.` Isn't this the common way to setup a cups server to offer its service to the local network? Then it should work out of the box with files shipped by the distribution. I can confirm that the cups webinterface can be accessed using "links http://localhost:631" via ssh on that system with only `network.target`. But it needs either a service restart or the `network-online.target` enabled to allow the local network access working.

Either my setup is not correct to work the way it should with only `network.target` or I would expect cupsd to detect any later change to the network and allow the desired remote access.

I haven't seen any delay reported by Arch users with `network-online.target` used. But I guess it's more a workaround.

**Comment by zdohnal** [comment]
Aha, I guess I misunderstood the issue - I thought you have a problem on the client, not on the server.

Then it makes more sense. We have a downstream patch in Fedora (planning to send it upstream in a while) to use ```IP_FREEBIND``` socket option which fixes this behavior according to (systemd documentation)[https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/]

**Comment by michaelrsweet** [comment]
@andyrtr The "normal" way to enable remote access (for printer sharing, etc.) is to listen on the "any" address (*), either using the Listen directive or the Port directive:

```
Listen *:631

Port 631
```

Listening to a specific address can lead to the kind of failures that you are seeing. As I recall, there was an old feature request to be able to listen to all addresses for a given network interface, and to adapt to interface changes, but that request was never implemented due to a lack of OS support. Even now, using DBUS notifications would only work on platforms that use systemd-networkd (often true for desktop/server systems, not so much for embedded systems/NAS boxes that care about networking standards conformance...)

**Comment by andyrtr** [comment]
> Aha, I guess I misunderstood the issue - I thought you have a problem on the client, not on the server.
> 
> Then it makes more sense. We have a downstream patch in Fedora (planning to send it upstream in a while) to use `IP_FREEBIND` socket option which fixes this behavior according to [systemd documentation](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/).

**Comment by andyrtr** [comment]
@zdohnal - the clients can't access the servers webinterface and can't print to the servers printer queues until the cups server on the server has been restarted.

@michaelrsweet: This is confusing to me.
`Listen 192.168.1.90:631` can be accessed by clients after the daemon restart but
with either
`Listen *:631` or `Port 631` or both together the server cannot be reached even after daemon restart.

**Comment by andyrtr** [comment]
@zdohnal - I guess it's this patch here: https://src.fedoraproject.org/rpms/cups/blob/master/f/cups-freebind.patch

I'm going to try that one out if it helps.

**Comment by andyrtr** [comment]
@zdohnal - thanks for the hint. this patch makes it work. Now `network.target` + `Listen 192.168.1.90:631` works as intended. Feel free to push the patch.

@michaelrsweet - please reconsider the new release version. Our distribution package version comparison tool "vercmp" reports a version donwgrade 2.3.3 > 2.3.3op1. Why don't you use 2.3.4 or 2.4.0 ?

**Comment by michaelrsweet** [comment]
@andyrtr The issue with that patch is that it is sometimes useful to get an error if you try to bind to the wrong address. Usually that is an error (or a mistake, if you will), so it should require an explicit override.

Using `Listen *:631` or `Port 631` should work in all cases, unless you have some sort of security setting/firewall in place that prevents incoming connections without an explicit source (listen) address.

As for the versioning, OpenPrinting CUPS isn't replacing Apple CUPS. And in fact Apple *does* have a v2.3.4 that ships with their newest version of macOS (still not pushed to Github...) I'll bring this up amongst the OpenPrinting maintainers - an alternative would be a fourth version number (e.g. 2.3.3.1 instead of 2.3.3op1) but I know there are other environments that might have a problem with *that*... :/

**Comment by andyrtr** [comment]
> Using `Listen *:631` or `Port 631` should work in all cases, unless you have some sort of security setting/firewall in place that prevents incoming connections without an explicit source (listen) address.

Got it. `Listen *:631` doesn't work when there's also `Listen localhost:631` before in the configuration file. Maybe man cupsd.conf is misleading here saying 
 ```
Listen /path/to/domain/socket
            Listens to the specified address and port or domain socket path for connections.  **Multiple Listen directives can be  provided**
            to  listen on multiple addresses.  The Listen directive is similar to the Port directive but allows you to restrict access to
            specific interfaces or networks.
```

**Comment by michaelrsweet** [comment]
@andyrtr Maybe this should be made more explicit, however the issue of multiple Listen lines isn't that they aren't supported, it is just that `Listen *:631` binds to *all* IP addresses (so you can't have a duplicate address).

**Comment by michaelrsweet** [comment]
Reopening to track documentation change.

**Comment by michaelrsweet** [comment]
[master fc9167da3] Update cupsd.conf man page to talk about Listen * vs Listen address (Issue #53)

**Comment by zdohnal** [comment]
@michaelrsweet Doesn't setting ```Port 631``` in ```cupsd.conf``` have a downside of opening the port for wide internet if the server has a IP which is reachable via wide internet?
I know this can be narrowed down by setting ```Allow from``` to a proper subnet, but still clients from outside can connect to the port and send a bunch of requests, which will keep ```cupsd``` busy when throwing them away, right?

I started using 'Listen <IP>:631' to prevent possible requests from outside since I read the article about how many print servers are reachable on the wider internet (about half a year ago or so), I thought it is the correct solution for this + setting ```Allow from``` properly.

**Comment by michaelrsweet** [comment]
@zdohnal The vast majority of systems running CUPS are going to be behind a router that does NAT and provides basic firewall capabilities. That combined with the default Deny all/Allow @LOCAL ACLs will quite effectively limit access to the LAN.

Limiting the Listen to the address of the (only) network interface in that configuration doesn’t make it more secure since remote access is being limited by the router and *not* by cupsd. Then it comes down to whichever holes you decide to configure, e.g., so-called DMZ hosts.

Indeed, a far more common problem is not making things open enough and dealing with any onboard firewall configuration underneath cupsd...

DoS attacks from the Internet are only a problem if you are “brave” enough to provide a public-facing print server. In my experience those public-facing servers are a result of misconfiguration or trying to do everything with a single server. Using Listen with an address in those situations won’t help unless the server in question has multiple physical network interfaces.

**Comment by zdohnal** [comment]
> DoS attacks from the Internet are only a problem if you are “brave” enough to provide a public-facing print server. In my experience those public-facing servers are a result of misconfiguration 

By misconfiguration you mean network's misconfiguration right? Or cupsd's?

> or trying to do everything with a single server.

If that's the case, is there any other mitigation than other network interface and configuring cupsd to listen on only that selected interface? (meaning settting cupsd to listen on IP which is assigned to the interface)

> Using Listen with an address in those situations won’t help unless the server in question has multiple physical network interfaces.

**Comment by michaelrsweet** [comment]
@zdohnal By misconfiguration I mean the network (router), or the server, or cupsd. It can happen anywhere, and usually the first step is "I can do this all on a single server with a single physical interface". The first rule of network security is that you don't connect a server to a network unless you want it accessible via that network.

The place for Listen is on multi-interface servers, e.g.:

```
LAN (private IP) <--eth0--> Server <--eth1--> Internet/WAN (public IP)
```

*If* you had such a server (and I am by no means recommending this configuration!) you can configure cupsd to only listen on its private IP over eth0 with appropriate allow/deny lines and server firewall configuration. Provided you don't get caught by side-channel or proxy attacks (...) this will effectively limit cupsd traffic to the LAN. Mind you, the server itself can be attacked from the public-facing interface, potentially exposing job history/files and other sensitive information, which is why you don't use this configuration if you care about security.

Things like Docker containers, virtual machines, and other VPS solutions are more commonly used to provide isolation and flexibility, and there you are back to using "Listen *:631" or "Port 631"...

(I *have* seen Listen used to provide multiple cupsd instances on a single server with multiple interfaces/addresses to support different organizations/groups and isolate printers and jobs, but these days you can spin up a Docker container for that much more easily and without the hassle of creating multiple cupsd configurations on a single OS image...)

**Comment by zdohnal** [comment]
Thank you for the explanation! Then the baseline is 'don't do everything on one server if the server is public one, or you may experience various problems.' :)
