### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by kloczek** [OpenPrinting/cups#573]
https://github.com/OpenPrinting/cups/compare/v2.4.2...master shows +130 commits since last release.
Is it possible to make new version soon? 🤔

**Comment by zdohnal** [comment]
There are two regressions since CUPS 2.4.2 release which I want to tackle before release:

https://bugzilla.redhat.com/show_bug.cgi?id=2094530
https://github.com/OpenPrinting/cups/pull/461

and then clean up the PRs.

My hope is to manage it this week before I go on vacation, otherwise after I'm back in January

**Comment by flux77** [comment]
Can the maintainers release a new version? Users of CUPS version 2.4.1 and 2.4.2 are stuck with either grayscale printing or color printing. The problem has since been fixed in CUPS' master branch but the vast majority of users are still affected by the problem due to the lack of a release. #401 #421

**Comment by luisvalenzuelar** [comment]
I am stuck and workaround does not work. I wrote [here](https://github.com/OpenPrinting/cups/issues/421#issuecomment-2010491590).
