### ISSUE TITLE
Add Option to Disable System Keychain on macOS

### ISSUE THREAD

**Issue by sjoubani** [OpenPrinting/cups#606]
**Is your feature request related to a problem? Please describe.**
See also https://github.com/apple/cups/issues/6037, this continues to be an issue on recent versions of macOS. It would help to be able to prevent CUPS-based targets from choosing inappropriate TLS credentials, as they will be unable to start TLS connections. Many Macs acting as print servers also host other services, and therefore are likely to have candidate identities in the System keychain, which aren't intended for CUPS.
The current mechanism in `tls-darwin.c` doesn't respect identity preferences (which are one solution), enumerate multiple matches as candidates, nor attempt to preflight the credential selected. Extracting the relevant code and running it repeatedly shows a different credential may be selected each time if many are available, which is also undesirable.

**Describe the solution you'd like**
A global option (like `-o system-keychain=no`) to cause `http_cdsa_open_system_keychain` to always return NULL/nil.

**Describe alternatives you've considered**
Custom builds, removing certificates, granting access conditionally, interposing.

**Additional context**
When running CUPS-based targets as Launch Daemons on macOS, the System keychain is always available, whereas user substitution in a graphical session doesn't produce the same result.

**Comment by michaelrsweet** [comment]
Not using the keychain is, unfortunately, not an option since macOS depends on it when generating self-signed certificates (the iOS target can generate and use an in-memory certificate since it lacks the same keychain APIs). I'm not sure what state your keychain is in that a query will result in multiple certificates matching the query, but this is the same code shipped by Apple and I'm not keen on changing it here when the code will never get used on macOS... :/

If you can provide additional context we might be able to come up with a short-term solution. Longer term CDSA/Security.framework support has been removed from CUPS 3.0 (replaced by a requirement for OpenSSL/LibreSSL or GNU TLS) since Securty.framework's TLS API was never updated to support TLS/1.3 (!) and the suggested Apple replacement (Network.framework) requires adoption of GCD and doesn't support TLS upgrade, both of which are a non-starter...

**Comment by michaelrsweet** [comment]
Closing as not to be fixed - CUPS 2.5 and later will no longer support Security.framework or the system keychain (opting to use OpenSSL/GNU TLS instead with standard PEM-encoded certs/keys).
