### ISSUE TITLE
ipp-usb: cannot print on HP m28a on ArchLinux

### ISSUE THREAD

**Issue by rilian-la-te** [OpenPrinting/cups#614]
from /var/log/ipp-usb/device.log

```
10-07-2022 21:04:57:   USB[0]: connection allocated, 1 in use: a-- --- ---
10-07-2022 21:04:57:   HTTP[074]: connection 0 allocated
10-07-2022 21:04:57: > USB[0]: write: wanted 976 sent 976 total 976
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 0 total 0
10-07-2022 21:04:57: ! USB[0]: zero-size read
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 1024 total 1024
10-07-2022 21:04:57: < HTTP[074]: POST http://localhost:60000/ipp/print - 200 OK
10-07-2022 21:04:57: < HTTP[074]: HTTP response header:
10-07-2022 21:04:57: <   HTTP/1.1 200 OK
10-07-2022 21:04:57: <   Content-Length: 981
10-07-2022 21:04:57: <   Content-Type: application/ipp
10-07-2022 21:04:57: <
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 0 total 1024
10-07-2022 21:04:57: ! USB[0]: zero-size read
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 0 total 1024
10-07-2022 21:04:57: ! USB[0]: zero-size read
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 0 total 1024
10-07-2022 21:04:57: ! USB[0]: zero-size read
10-07-2022 21:04:57: < USB[0]: read: wanted 4096 got 28 total 1052
10-07-2022 21:04:57: < HTTP[074]: response body: got 981 bytes; EOF
10-07-2022 21:04:57:   USB[0]: connection released, 0 in use: --- --- ---

```

keep-alive quirk is set for M28a.

**Comment by tillkamppeter** [comment]
Sorry, I have overlooked this, probably because it was still assigned to ipp-usb.

The actual problem is in the PPD file generators for driverless printing. All of them, the one in CUPS 2.x used by temporary queues and queues created with `-meverywhere`, the one of cups-filters 1.x used by `driverless` 1.x and `cups-browsed` 1.x, and also the one in libppd 2.x, used by `driverless` 2.x and `cups-browsed` 2.x, have this bug.

I have already found fix and this is very simple. The problem was that if a driverless printer reports `print-color-mode-default` set to `auto` all the three PPD generators have set the default for the `ColorModel` option to `RGB`, regardless whether `RGB` is actually an available choice, for example on monochrome printers. This makes all jobs not printing on such printers where the user does not explicitly set `ColorModel` to `Gray` or `print-color-mode` to `monochrome`.

In CUPS I have already committed the fix: ebf3bb82.

**Comment by tillkamppeter** [comment]
Committed fix to libppd 2.x: ae345c3a

**Comment by tillkamppeter** [comment]
Committed fix to cups-filters 1.x: OpenPrinting/cups-filters@9799398

**Comment by tillkamppeter** [comment]
@rilian-la-te thanks a lot for your report and for your great cooperation in investigating this problem!
