### ISSUE TITLE
The printer edits are cut off at the top and bottom after upgrade cups

### ISSUE THREAD

**Issue by T0unet** [OpenPrinting/cups#630]
The background,
We're upgrading a technical platform for our ERP that sends postscript editions in A4.
Our old cups --> Redhat 6.1 / Cups 1.4.2 / Foomatic 4.0.4
New platform --> OL 8.7 / Cups 2.2.6 / Foomatic 4.0.12

We use the same driver for all our printers, "Generic PCL 6/PCL XL Printer Foomatic".

We kept all the settings of the old cups (a few hundred printers configured).
On the new cups, the top and bottom of the page are cut off, about 1.3 cm (1/2 inch).

There are no specific settings on the lpoptions side. 
The tests performed
- old erp to new cups --> page cut. 
- new erp to new cups --> page cut.
- old erp to old cups --> ok (obviously, this is our current production)
- new erp to old cups --> ok 

I tried to put a lpoptions setting on a particular printer (e.g.` lpoptions -p printtest -o page-bottom=0 -o page-left=0 -o page-right=0 -o page-top=0`), no change.

I tried to take the ppd of the printer on the old cups (which is slightly different because foomatic has evolved a bit), no change.

If I take the ps file from the ERP, and send it to my printer:
`lpr -P printtest testfromnewcups.ps` --> cut file

If I take the PDF file that is generated in our erp and send it :
`lpr -P printtest testfromnewcups.pdf` --> uncut file ( ?! )
So for a PDF, the file doesn't pass the cups filters?

If I take the ps file out of the ERP, and send it to my printer in raw mode :
`lpr -P printtest -o raw testfromnewcups.ps` --> uncut

Anyway, I'm missing something but maybe someone can help me?

**Comment by zdohnal** [comment]
Hi,

CUPS 2.2.6 is several years old, please contact your OS support for further help.

Either way I suggest to turn debug logging on by ```cupsctl LogLevel=debug2```, try to print PS file again and check the logs - based on your findings the problem is in a filter which is started only if you send the PS file for normal printing, so you can check which filter is run when you print PS and which is not when you print PDF. It will help your OS support to locate the issue.
