### ISSUE TITLE
Xerox WorkCentre 6515 Printing Double

### ISSUE THREAD

**Issue by Richard-ES** [OpenPrinting/cups#645]
I have been using Linux Mint now for 6 or 7 years and recently I upgraded to v21.1.  Since then I have had a strange issue with my wireless printer, a Xerox WorkCentre 6515. I use driverless CUPS (2.4.1) and while the OS finds the printer, no problem, and set up appears to go very smoothly, now, whenever I print to it from my PC (a Dell Latitude E7250) - single or double sided - it always prints out two copies, even if I actively choose 1 copy, I always get 2  (this didn't happen on Mint v20.x). When my wife prints to the same printer using her Apple Mac, this never happens; and it doesn't happen when I print to it from a family Windows 11 PC. I have tried to force CUPS to use a Xerox Linux ppd driver: ~/opt/XeroxOffice/prtsys/ppd/XROFFSTD.ppd, by using the CUPS localhost site, but this stops the printer from working at all for me.

Doing a bit more digging, I find that whenever I print a document (e.g. a PDF via Document Viewer or a LibreOffice doc), I can find the job in the CUPS folder: ~/var/spool/cups. The job filename is derived from the Xerox Print Job number, e.g. c00368 is the Xerox Print Job #368. For some reason, while the job is active a phantom job file named almost the same as the cups file is created in the same cups folder. So Xerox print job #368 initially creates two files, once called called d00368-001 and one called c00368.  File d00368-001 has an icon very much like an Adobe file icon. After a while a second, duplicate document prints, with no intervention by me. The d00nnn-001 file then just lingers in the folder. However, if you delete the d00nnn-001 file after the printer "dings" to say the first job has finished, and before the second printout, the duplicate doesn't happen. Can anyone explain what is going on and how to stop it happening?!

Thank you.

**Comment by zdohnal** [comment]
Hi @Richard-ES ,

please follow https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md and provide the requested information.

> Doing a bit more digging, I find that whenever I print a document (e.g. a PDF via Document Viewer or a LibreOffice doc), I can find the job in the CUPS folder: ~/var/spool/cups. The job filename is derived from the Xerox Print Job number, e.g. c00368 is the Xerox Print Job #368. For some reason, while the job is active a phantom job file named almost the same as the cups file is created in the same cups folder. So Xerox print job #368 initially creates two files, once called called d00368-001 and one called c00368.

'c' file is a control file for the job, which contains attributes which are used during processing in CUPS, while 'd' file is the file the application sent for printing, so if you remove the 'd' file, CUPS can't process further.

The problem is that some part of the chain generates two copies or send an option which causes creating two copies - I can't tell which one until you provide the requested info from the link.

**Comment by Richard-ES** [comment]
Hi @zdohnal ,

Thanks for the quick response.  Below are the answers (as best I can give them) to the questions posed here https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md:

1. Linux Mint v21.1
2. CUPS version 2.4.1
3. N/A
4. See above. This morning I again set a single page, 1 copy pdf print job to the Xerox WorkCentre.  Without doing anything to the files in ~/var/spool/cups the printer gave me two copies!  Error_log.txt file from just after that print job completed attached; debugging had been turned on (see #7).
5. Xerox WorkCentre 6515
6. (i) See original post for description of the issue.  Also, I ran $ lpstat -e and $ lpstat -a and the printer is available and is accepting jobs.  Available options as follows:-

richard@richard-Latitude-E7250:~$ lpoptions -p Xerox-WorkCentre-6515 -l
PageSize/Media Size: 4x6 5x7 8x10 *A4 A5 A6 B6 Env10 EnvC5 EnvDL EnvMonarch Executive FanFoldGermanLegal Legal Letter Statement Custom.WIDTHxHEIGHT
InputSlot/Media Source: *Auto Tray1 Manual
MediaType/Media Type: *Auto Stationery Envelope Labels StationeryHeavyweight Cardstock StationeryFine CustomType1 CustomType2 CustomType3 CustomType4 CustomType5 StationeryHeavyweightCoated
ColorModel/Print Color Mode: Gray *RGB
Duplex/2-Sided Printing: *None DuplexNoTumble DuplexTumble
OutputBin/Output Tray: *FaceDown
cupsPrintQuality/Print Quality: *Normal High
print-content-optimize/Print Optimization: *auto graphics text text-and-graphics
print-scaling/Print Scaling: *auto auto-fit fill fit none

6. (ii) The issue happens with all documents printed to that printer via CUPS (e.g. via Document Viewer; LibreOffice)
6. (iii) Printing to the Xerox 6515 from another PC (running Windows or iOS) the issue does not arise.
6. (iv) N/A
7. CUPS debug logging had been turned on before the print job described earlier.
8. Done
9. [error_log.txt](https://github.com/OpenPrinting/cups/files/11146649/error_log.txt)
10. richard@richard-Latitude-E7250:~$ lpstat -t 
scheduler is running
system default destination: Xerox-WorkCentre-6515
device for Epson-ET-7700: ipp://EPSON%20ET-7700%20Series._ipp._tcp.local/
device for Xerox-WorkCentre-6515: ipps://Xerox%20WorkCentre%206515%20(8f%3A7b%3Ac1)._ipps._tcp.local/
Epson-ET-7700 accepting requests since Wed 11 Aug 2021 11:12:32 BST
Xerox-WorkCentre-6515 accepting requests since Tue 04 Apr 2023 09:56:14 BST
printer Epson-ET-7700 is idle.  enabled since Wed 11 Aug 2021 11:12:32 BST
printer Xerox-WorkCentre-6515 is idle.  enabled since Tue 04 Apr 2023 09:56:14 BST

richard@richard-Latitude-E7250:~$ lpinfo -v
network ipp
file cups-brf:/
network socket
network ipps
network beh
network http
network lpd
network https
direct hp
network smb
direct hpfax
network dnssd://EPSON%20ET-7700%20Series._ipp._tcp.local/?uuid=cfe92100-67c4-11d4-a45f-f8d027d2deab
network dnssd://Xerox%20WorkCentre%206515%20(8f%3A7b%3Ac1)._pdl-datastream._tcp.local/?uuid=15f9a510-1dd2-11b2-b2c2-9c934edd70eb
network ipps://EPSON%20ET-7700%20Series._ipps._tcp.local/
network ipps://Xerox%20WorkCentre%206515%20(8f%3A7b%3Ac1)._ipps._tcp.local/

11. A file called Xerox-WorkCentre-6515.ppd exists in /etc/cups/ppd, but I cannot include it in this comment (access denied on my laptop; and GitHub does not accept .PPD files)
12. Happens with every file
13. Saved the 'd' file as .docx so that I could upload here.
[d00382-001.docx](https://github.com/OpenPrinting/cups/files/11147009/d00382-001.docx)
14. Seems to be a particular issue with LibreOffice files.

I hope this helps.  If you have any other questions, please let me know.  And thanks, in anticipation, for your help!

**Comment by zdohnal** [comment]
@Richard-ES thank you for the data!

Ad 6 (i) - have you tested printing by ```lp -d Xerox-WorkCentre-6515 <file>``` ?

Ad 11 - you should be able to access the file with sudo - then you can copy it and rename it to have .txt suffix, which Github accepts. The document - https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md - mentions it as well right under *How to report issue*:

```
use attachments for blocks of text longer than 10 lines - put the text into a file, rename it to have .txt suffix and click on pasting them string under comment box in the issue
```

Ad 13 and 11 - the job file has to match the job which is in the error_log - unfortunately they are different, which complicates debugging.

Ad driverless - since your printers are driverless, you don't have to install them at all (based on 'lpstat -t', you have them installed permanently) - it would be great if you tried the temporary queues and see whether they are affected as well.

Since your printer is driverless, it would be great to have its attributes as well - see https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md#information-requested-for-driverless-network-printers - this way I can fake your printer locally to some extent.

=================================================

What I have been able to find so far:

There are no specific `copies` attrs sent to the printer and all filters are run with copies parameter '1'. But what is interesting is this response from the printer:

```
D [04/Apr/2023:09:53:55 +0100] [Job 380] Processing page 1...
...
D [04/Apr/2023:09:53:55 +0100] [Job 380] Processing page 1...
```

which indicates there are two pages in the job - which I'm not able to verify, because the file from 13. is for job 382 and the logs are for job 380...

Another interesting find is that cupsd is restarted during job processing:

```
D [04/Apr/2023:09:54:09 +0100] [Job 380] (monitor) Get-Job-Attributes: successful-ok (successful-ok)
D [04/Apr/2023:09:54:09 +0100] [Job 380] (monitor) job-state = processing
D [04/Apr/2023:09:54:09 +0100] [Job 380] (monitor) job-state = processing
...
I [04/Apr/2023:09:54:10 +0100] Scheduler shutting down normally.
...
d [04/Apr/2023:09:55:41 +0100] cupsdCheckJobs: Job 380 - dest="Xerox-WorkCentre-6515", printer=(nil), state=3, cancel_time=0, hold_until=0, kill_time=0, pending_cost=0, pending_timeout=0
d [04/Apr/2023:09:55:41 +0100] start_job(job=0x557d1028f480(380), printer=0x557d102778b0(Xerox-WorkCentre-6515))
...
d [04/Apr/2023:09:55:41 +0100] cupsdContinueJob(job=0x557d1028f480(380)): current_file=0, num_files=1
D [04/Apr/2023:09:55:41 +0100] [Job 380] 5 filters for job:
D [04/Apr/2023:09:55:41 +0100] [Job 380] pdftopdf (application/pdf to application/vnd.cups-pdf, cost 66)
...
```

So because the job is not finished before the restart, it is restarted as whole.

Have you restarted the cupsd process manually? Or was it the time when you played with 'd' file?

Either way, since the 'd' file and logs don't match, I'm not able to say whether the original file had two pages or not (because printer reports processing of two pages - the critical info is whether the original document has two pages or filters created a dupe), which plays a critical role whether the cupsd restart caused the duplication or not...

**Comment by Richard-ES** [comment]
Hi @zdohnal  - You are most welcome :-)

To answer your questions:-
- Ad 6 (i) - have you tested printing by lp -d Xerox-WorkCentre-6515 <file> ?
   - When I type this: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox-WorkCentre-6515 Test.pdf, the file prints (request id is Xerox-WorkCentre-6515-383 (1 file(s)) - 2 copies of a single sheet
   - When I type this: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox-WorkCentre-6515 Test.docx, the file does not print and I get this message: lp: Unsupported document-format "application/vnd.openxmlformats-officedocument.wordprocessingml.document".

- Ad 11. I opened the file called Xerox-WorkCentre-6515.ppd in /etc/cups/ppd as Root, and copied and pasted the contents into this text file: 
[Xerox-WorkCentre-6515.txt](https://github.com/OpenPrinting/cups/files/11157850/Xerox-WorkCentre-6515.txt)

- Ad 13 and 11.  I am unable to post a new error_log file today - I think the filesize is too big (>14MB).  And I now have to go and do something else.  I am very sorry.  I will post a new error_log file and 'd' file as soon as I can (it might be a day or two).

Thanks in advance for your help, and apologies I can't get you everything today.  It's taking me longer than I thought to get the files.

**Comment by zdohnal** [comment]
>     * Ad 6 (i) - have you tested printing by lp -d Xerox-WorkCentre-6515  ?
>       
>       * When I type this: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox-WorkCentre-6515 Test.pdf, the file prints (request id is Xerox-WorkCentre-6515-383 (1 file(s)) - 2 copies of a single sheet
>       * When I type this: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox-WorkCentre-6515 Test.docx, the file does not print and I get this message: lp: Unsupported document-format "application/vnd.openxmlformats-officedocument.wordprocessingml.document".

Ok, so permanent queue is always affected. .docx files are from windows, so CUPS based on Unix does not have support for it.

> 
>     * Ad 11. I opened the file called Xerox-WorkCentre-6515.ppd in /etc/cups/ppd as Root, and copied and pasted the contents into this text file:
>       [Xerox-WorkCentre-6515.txt](https://github.com/OpenPrinting/cups/files/11157850/Xerox-WorkCentre-6515.txt)

Thank you! Looks quite small.

> 
>     * Ad 13 and 11.  I am unable to post a new error_log file today - I think the filesize is too big (>14MB).  And I now have to go and do something else.  I am very sorry.  I will post a new error_log file and 'd' file as soon as I can (it might be a day or two).
> 

Before you reproduce the issue, you can use 'tail -f' for getting the logs on the run, and after the problem happens, kill the process. This way you will get much smaller file.

```
$ sudo tail -f /var/log/cups/error_log > debug_log.txt &
(reproduce the issue)
$ sudo kill $(pidof tail)
```

> 
> Thanks in advance for your help, and apologies I can't get you everything today. It's taking me longer than I thought to get the files.

Np, please don't forget to try the temporary queue and get attr.log file from https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md#information-requested-for-driverless-network-printers .

```
$ lp -d Xerox_WorkCentre_6515_8f_7b_c1 <a file>
$ ipptool --ippserver attr.log.txt -v ipp://192.168.68.119/ipp/print get-printer-attributes.test
```

**Comment by Richard-ES** [comment]
Hi @zdohnal,

Thanks for your patience and your help so far.  OK to answer/address your points above:-

1. I ran 'tail -f' as instructed then repeated the issue and here is the debug_log.txt zipped-up (the native debug_log.txt file was over 20MM)
[debug_log.txt.gz](https://github.com/OpenPrinting/cups/files/11170718/debug_log.txt.gz)

2. Here is the 'd' file (renamed to .docx) associated with the issue captured in the debug_log.txt
[d00394-001.docx](https://github.com/OpenPrinting/cups/files/11170738/d00394-001.docx)

3. I ran: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox_WorkCentre_6515_8f_7b_c1 Test.pdf and the file printed (for some reason the issue didn't happen this time - the job only printed one copy!!, i.e. the issue didn't happen).

4. Then I ran: richard@richard-Latitude-E7250:~$ ipptool --ippserver attr.log.txt -v ipp://192.168.68.119/ipp/print get-printer-attributes.test.  The attrlog.txt file is here:-
[attr.log.txt](https://github.com/OpenPrinting/cups/files/11170769/attr.log.txt)

Hopefully that gives you some more to work on.  Just so you know, as I have been going through what you have asked me to do, on occasions the double-print issue does not happen!  I can find no pattern -  which type of file, or when.  I have been using a small test pdf file mostly, and that now sometimes shows the issue, sometimes not.  A test .docx file (which, BTW, I am opening and editing using LibreOffice, not MS-Word)  often seems to be a problem, but a test .odt file seemed OK.  It's been rather frustrating.  One thing I have noticed, if the "double printing" is going to happen, the window which opens if you select "Printers" (the one which has icons to represent each printer available to the OS) has a second printer icon with a "No Entry" flag on it.  This icon  disappears when the second prinotut job has completed. See screenshot:-

![Screenshot from 2023-04-06 13-54-30](https://user-images.githubusercontent.com/29749953/230385465-0ffa7b03-8c0e-461d-9217-8b2bb6a92ee9.png)

I have no idea if this is relevant, but I thought I would just let you know.

Thanks again - and good luck trying to find out what is going on here.

**Comment by zdohnal** [comment]
>     3. I ran: richard@richard-Latitude-E7250:~/Downloads$ lp -d Xerox_WorkCentre_6515_8f_7b_c1 Test.pdf and the file printed (for some reason the issue didn't happen this time - the job only printed one copy!!, i.e. the issue didn't happen).
> 

Ok, so the dupe is created when you use driver generated from cups-filters via permanent queue. I will look into it as well.

But based on your setup (your mDNS is working and your printers are visible) I highly recommend to remove the permanent printers  Xerox-WorkCentre-6515 and Epson-ET-7700 and use their temporary printer variants, since those aren't affected.

The temporary printers are fully supported in CUPS and main applications (PDF viewer, Firefox, Libreoffice), so you should be ok - in case you find an issue with them, try printing via ```lp``` first and if it works, report the issue to the application.

**Comment by zdohnal** [comment]
I've run the filter chain by hand and a duplicit page wasn't created - IMO it is not a duplicit page, but the restarted job, because cupsd restarts in the middle of the job - I'm not able to find out why.

Since IMO you don't restart cupsd by hand during the printing, so I guess it is triggered by a SIGTERM from the another process. Please contact your distro maintainers for further help with this, in case you want to use permanent queues.

I'm sorry for inconvenience.

**Comment by Richard-ES** [comment]
Thanks for all your help  @zdohnal.  I will try and pass this all over to the Mint developers (I did flag the issue with them to begin with, but got no response).  But your suggestion to use the temporary printer variant does seem to work (only one pdf tried so far), so thank you for that tip!

All the best - and carry on the good CUPS work! :-)

**Comment by Richard-ES** [comment]
Thanks for all your help  @zdohnal.  I will try and pass this all over to
the Mint developers (I did flag the issue with them to begin with, but got
no response).  But your suggestion to use the temporary printer variant
does seem to work (only one pdf tried so far), so thank you for that tip!

All the best - and carry on the good CUPS work! :-)

Regards,

Richard-ES
