### ISSUE TITLE
Webinterface - is it necessary for CUPS 3.0?

### ISSUE THREAD

**Issue by chalmerssys** [OpenPrinting/cups#651]
Hi,

This is sort of a bug-report, but I don't care much if it's fixed or not. 

If I turn on the web interface of our CUPS-server the result is very high CPU-load.
The server has about 200+ printers. Since I don't like or need the webinterface I just disable it, problem solved.

According to https://github.com/OpenPrinting/cups/wiki/CUPS-3.0 you will keep the web interface in the upcoming Sharing server. Would it not be a good idea to dump the the web interface and instead focus on improving command line utilities (for sysadmins) or GUI-interfaces (for users)?  

Just a suggestion...

**Comment by zdohnal** [comment]
Hi,

nowadays it is common to have not just CLI tools, but automation (scripts which will automatically set up your machine, f.e. automatically install N printers) and Web Interface as well for sysadmins, because it flattens the learning curve if a new sysadmin comes into a company instead of studying man pages and working in terminal all the time.

So a web interface over cupsd is one of the requirements - currently only web interface is provided by CUPS, so if we drop it, there has to be a graphical replacement already. One of the candidates is cockpit project, but last time I spoke with them (approx 5 years ago) they don't plan to add printing interface - so we would have to talk to them whether they would at least accept our implemented web UI before we start any migration/removal work.

Either way I would recommend checking error_log and access_log - turning off web interface closes the server from one set of requests, so if CPU goes down with turning off web UI, there might be clients which send unexpected number of requests, which causes high CPU load. Or it can be a bug, which we are interested in.
