### ISSUE TITLE
no good !

### ISSUE THREAD

**Issue by Tweetybird5430** [OpenPrinting/cups#676]
You cannot find my hp 2700 wifi printer

**Comment by zdohnal** [comment]
Hi,

your printer supports AirPrint (if it is HP DeskJet 2700 from this list https://support.apple.com/en-us/HT201311 ), which means CUPS finds it if AirPrint support is enabled in printer and your OS has mDNS support. You can verify this by looking into its web interface or manually by commands:

```
$ nc -vz <printer_ip> 631
$ ipptool -tv ipp://<printer_ip>/ipp/print get-printer-attributes.test
$ avahi-browse -avrt 
```

where you put printer's IP instead of <printer_ip> - if the previous test fails, the following will fail as well. The first test checks whether the IPP port is opened, the second checks if the printer responds correctly and the last shows all mDNS devices on your local network - the printer has to be among them to be found automatically.

If the first test fails, go to the printer web ui and enable IPP/Airprint settings. Once IPP port is enabled, the second command should pass - if it doesn't, check the printer's ui for more IPP related settings to enable, or it might be a firmware bug (in this case please report to HP). And at last, if the device is not in list of mDNS devices, check mDNS settings at printer, your firewall settings regarding mDNS and mDNS support in your OS in general (you should be able to ping the any .local address) - regarding mDNS problems please contact your OS support.
