### ISSUE TITLE
[Feature Request] RESTful API

### ISSUE THREAD

**Issue by yarons** [OpenPrinting/cups#68]
Hi,
I've already suggested developing a RESTful API for cups on Apple's repository but I think it's worth mentioning here as well:
https://github.com/apple/cups/issues/5869

**Comment by michaelrsweet** [comment]
@yarons That would be a hard no. CUPS uses the Internet Printing Protocol for that (which is HTTP POSTs using a compact binary encoding vs. JSON or some other webby format) and there is a node.js API for speaking IPP.

Adding a RESTful API would be a step backwards in capability and interoperability.

**Comment by yarons** [comment]
It doesn't have to replace, it can compliment.

**Comment by michaelrsweet** [comment]
Why would we bother? It would only increase the attack surface area, add yet another interface for us to support, and not add a single functional capability to CUPS.

You can always implement a CGI program/script that acts as a RESTful endpoint. We just don't want to be stuck supporting it.

**Comment by yarons** [comment]
Basically because it's one of the most used internet standards but if I can't create it I'm not going to insist, thank you.

**Comment by michaelrsweet** [comment]
The problem with RESTful is that it *isn't* an internet standard. It is a common design pattern that has been abandoned for standardization because it lacks schema and other things that make it possible to standardize the interface and have interoperability. IPP came early and adopted a custom binary message encoding rather than XML. Today it would likely use CBOR, which is a binary encoding compatible with JSON and provides schema support...

Anyways...

**Comment by yarons** [comment]
Should I open another feature request about that? 😄
