### ISSUE TITLE
Cups attempts to probe, configure unsupported Canon CAPT USB printers

### ISSUE THREAD

**Issue by chrisbainbridge** [OpenPrinting/cups#80]
cups version: 2.3.3op1-7

Cups does not support Canon CAPT USB printers (this requires a proprietary
driver which uses /dev/usb/lp0), but these printers are not blacklisted, so
when one is plugged in, cups sets up a new, non-functional printer, and
probes the USB device, the kernel logs a USB disconnect, and disrupts
operation of the Canon driver. Running lpinfo/lpstat also seems to do some probe
and cause a USB device disconnect. The kernel logs:

`Jan 23 23:45:29 debian kernel: usblp0: removed`

It appears the fix would be to add Canon CAPT printers to
/usr/share/cups/usb/org.cups.usb-quirks as so:

```
# Canon, Inc. LBP810 Printer
0x04a9 0x260a blacklist

# Canon, Inc. LBP1120 Printer
0x04a9 0x262b blacklist

# Canon, Inc. LBP1210 Printer
0x04a9 0x2617 blacklist

# Canon, Inc. LBP2000 Printer
0x04a9 0x260e blacklist

# Canon, Inc. LBP2900/LBP2900B Printer
0x04a9 0x2676 blacklist

# Canon, Inc. LBP3000 Printer
0x04a9 0x266a blacklist

# Canon, Inc. LBP3010/LBP3018/LBP3050 Printer
0x04a9 0x26da blacklist

# Canon, Inc. LBP3100/LBP3108/LBP3150 Printer
0x04a9 0x26db blacklist

# Canon, Inc. LBP3200 Printer
0x04a9 0x2636 blacklist

# Canon, Inc. LBP3210 Printer
0x04a9 0x2657 blacklist

# Canon, Inc. LBP3250 Printer
# CAPT printer with unknown USB ID
# 0x04a9 0x???? blacklist

# Canon, Inc. LBP3300 Printer
0x04a9 0x267e blacklist

# Canon, Inc. LBP3310 Printer
0x04a9 0x26b9 blacklist

# Canon, Inc. LBP3500 Printer
0x04a9 0x268b blacklist

# Canon, Inc. LBP3600 Printer
0x04a9 0x2654 blacklist

# Canon, Inc. LBP5000 Printer
0x04a9 0x2679 blacklist

# Canon, Inc. LBP5050 Printer
0x04a9 0x26ba blacklist

# Canon, Inc. LBP5100 Printer
0x04a9 0x26a4 blacklist

# Canon, Inc. LBP5200 Printer
0x04a9 0x266e blacklist

# Canon, Inc. LBP5300 Printer
0x04a9 0x26a1 blacklist

# Canon, Inc. LBP6000/LBP6018 Printer
0x04a9 0x271a blacklist

# Canon, Inc. LBP6020 Printer
0x04a9 0x2771 blacklist

# Canon, Inc. LBP6230/LBP6240 Printer
0x04a9 0x2796 blacklist

# Canon, Inc. LBP6200 Printer
0x04a9 0x271b blacklist

# Canon, Inc. LBP6300 Printer
# Possibly also: LBP6300n LBP6310dn
0x04a9 0x26ff blacklist

# Canon, Inc. LBP7010C/7018C Printer
0x04a9 0x271c blacklist

# Canon, Inc. LBP7200C Printer
# Possibly also: LBP7200Cdn
0x04a9 0x26f1 blacklist

# Canon, Inc. LBP9100C Printer
0x04a9 0x26ea blacklist
```

(as originally reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980973)

**Comment by michaelrsweet** [comment]
@chrisbainbridge Blacklisting these Canon printers won’t help with keeping the kernel driver loaded. As soon as somebody has another USB printer connected it will cause the same problem since the legacy kernel driver cannot be loaded when the USB backend is being used - they both try to claim the same USB devices.

First, the Canon driver needs to be fixed to actually work with CUPS and not work around it.

Second, we should determine why the CUPS USB backend is not compatible with these Canon printers - in my experience the CUPS backend usually does a better job and is less problematic than the usblp driver. If they need quirk rules, then we should add them. But blacklisting in order to use usblp isn’t the reason for the blacklist - that “quirk” is meant for USB printers that don’t actually conform to the USB printer class specification but reuse the class number for their own purposes (and thus don’t work with the CUPS backend *or* usblp).

**Comment by chrisbainbridge** [comment]
> @chrisbainbridge Blacklisting these Canon printers won’t help with keeping the kernel driver loaded. As soon as somebody has another USB printer connected it will cause the same problem since the legacy kernel driver cannot be loaded when the USB backend is being used - they both try to claim the same USB devices.

Ok, I had read that the legacy driver and libusb driver can coexist in this [old comment from Till Kamppeter](https://bugs.launchpad.net/ubuntu/+source/cups/+bug/902970/comments/12): _"On one computer a printer using a proprietary kernel-module-based backend and a printer using the libusb-based standard backend can be used in parallel (they can even print at the same time)"_. Perhaps that is not the case anymore?

If /dev/usb/lp0 is being used by the Canon CAPT driver, and the USB IDs of Canon CAPT printers are blacklisted so cups won't touch a CAPT printer, wouldn't this prevent the issue of cups trying to take over the connection and claim the printer? If a second non-CAPT printer is connected, then wouldn't cups operate as normal, and take over the connection?

> 
> First, the Canon driver needs to be fixed to actually work with CUPS and not work around it.
> 
> Second, we should determine why the CUPS USB backend is not compatible with these Canon printers - in my experience the CUPS backend usually does a better job and is less problematic than the usblp driver. If they need quirk rules, then we should add them. But blacklisting in order to use usblp isn’t the reason for the blacklist - that “quirk” is meant for USB printers that don’t actually conform to the USB printer class specification but reuse the class number for their own purposes (and thus don’t work with the CUPS backend _or_ usblp).

It would be good to have a better solution but it may not be possible/practical. As far as I know, CAPT printers are not functional without the Canon ccpd daemon which uses the legacy /dev/usb/lp0 type devices. The packages from Canon install a cups backend to /usr/lib/cups/backend/cnusb which forwards printer instructions over TCP to ccpd. ccpd is closed source so can't be modified to use libusb, and even if it could, it couldn't be integrated with cups due to the closed source libraries it requires.

There have been several attempts at creating a functional open source replacement for the CAPT driver (e.g. [captdriver](https://github.com/agalakhov/captdriver), surprisingly still ongoing after 8 years) but unfortunately these haven't been so successful.

**Comment by michaelrsweet** [comment]
@chrisbainbridge The functionality offered by libusb is to detach and re-attach kernel drivers from a particular USB device before claiming (using) the device, which theoretically allows usblp to co-exist but depends on the printers correctly supporting USB...

Anyways, as I mentioned before blacklisting is not the solution. If scanning the USB bus for printers is enough to break these printers, then basically every printer application on the system (be it CUPS with legacy printer drivers or the flood of new CUPS Printer Applications that will be coming out over the next year or so) is going to "break" them. As for the auto-add behavior, that is a question for the distributions not to eagerly try to setup anything that is connected to the USB bus but lacks a driver.

Printer applications may not support or be able to access the local CUPS USB quirks file (particularly once CUPS is shipped as a Snap or other "container" technologies that seem to be the way things are going), so we need to either determine which quirks are needed to make the CUPS USB backend cooperate with these printers or decide that these printers can simply not be supported on Linux. My hope is that there might be some common quirks that can be incorporated into the USB backend and PAPPL (a framework being used for the new CUPS Printer Applications that are replacing printer drivers) so that these old printers can coexist.

**Comment by michaelrsweet** [comment]
Closing this - I don't think we came to a satisfactory solution in general, but those playing along at home with one of these printers can add a file to the /usr/share/cups/usb directory (name doesn't matter) with the above list of printers. No guarantees that this will solve the problem since CUPS isn't the only program that accesses USB printers...

**Comment by TailsFanLOL** [comment]
@michaelrsweet, time traveller here. It doesn't break from CUPS probing for them. However, it is an inconvenience to wait out and close a DE provided "No drivers found" popup whenever the printer is turned on.

**Comment by ssokolow** [comment]
Thank you for mentioning this. All the instructions that I could google up were either for ipp-usb, not cups-browsed, or were for disabling ALL autodetection.

Tossing this into `/usr/share/cups/usb/org.cups.usb-quirks` and `chattr +i`-ing it so APT can't undo my change did the trick:

```
# EDIT: Prevent Brother P-Touch P700 from triggering popup complaining
# that I don't have the CUPS driver installed (I use `ptouch-print`)
0x04f9 0x2061 blacklist
```

**Comment by michaelrsweet** [comment]
@ssokolow You can also just create a separate file in that directory called "p700.usb-quirks" and you won't have to worry about apt blowing away your changes...

We should probably update the installed file to point people here and to create their own file for local changes...

**Comment by ssokolow** [comment]
Thanks. Definitely a more proper solution, but it's not just the installed file. It's also that this was the only result I got on Google or Perplexity that mentioned something applicable to cups-browsed but less drastic than turning it off or using udev to block all access to the USB device or what have you.

If not for this issue, I wouldn't have learned of the installed file.
