### ISSUE TITLE
Certificate guidance on  aws EC2 and load balancer

### ISSUE THREAD

**Issue by SridharSambu** [OpenPrinting/cups#812]
**Describe the bug**
we have installed cups on aws ec2 linux and a load balancer . is there any guidance on how to handle certs for cups which are behind the aws alb.

error message

"message": "self-signed certificate",
    "name": "Error",
    "stack": "Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)\n    at TLSSocket.emit (node:events:517:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at TLSSocket._finishInit (node:_tls_wrap:1017:8)\n    at ssl.onhandshakedone (node:_tls_wrap:803:12

**System Information:**
 - OS and its version: [RHEL 8.]
 - Application [e.g. chrome, safari, evince...]
 - CUPS version  1.6.3-52

**Additional context**
Follow the instructions from the [REPORTING-ISSUES](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md) document and provide all information regarding the issue.

**Comment by zdohnal** [comment]
I'm sorry, AFAIK there is no such guidance, only a basic one - CUPS can generate self-signed certificates or you can turn the creation off and use your own certificate.
Contact your OS support for more help, it will give you more precise advice.

**Comment by michaelrsweet** [comment]
@zdohnal We probably should add this to the documentation.

@SridharSambu The simplest solution is to use Let's Encrypt. Alternately you can generate your own (not self-signed) certificates. In either case just make sure that you have subjectAltName records for the primary hostname as well as the common "round robin" hostname, e.g., "server867.example.com" and "printing.example.com" where "printing.example.com" is the common name used by all of the servers. The key thing is that you not rely on self-signed certificates since clients will "pin" the last cert they saw for "printing.example.com" and error out if they connect to a different server in the pool.

**Comment by SridharSambu** [comment]
How can we turn off CUPS can generate self-signed certificates.?

**Comment by michaelrsweet** [comment]
@SridharSambu If the "hostname.crt" and "hostname.key" files are present in /etc/cups/ssl, then CUPS will use them rather than generating a self-signed certificate.
