### ISSUE TITLE
RFE:  port o openssl

### ISSUE THREAD

**Issue by kloczek** [OpenPrinting/cups#84]
At the moment much more software is possible to compile against openssl and much less against gnutls.
It would be good to have an optoopn to build cups agaist openssl to minimise number of used crypto/TLS backend libraries.

**Comment by michaelrsweet** [comment]
@kloczek OpenSSL support was removed from CUPS many years ago due to numerous security issues in OpenSSL at the time along with the relatively primitive and fragile API that is provided. OpenSSL's only advantage in the crypto field was that it was the first free implementation, which is why so many programs (CUPS included) added TLS support using it.

I am actually a big fan of the LibreSSL project, and they provide a modern crypto API in addition to the legacy OpenSSL API, but at the moment there is no easy way to create self-signed certificates with either OpenSSL or LibreSSL - you need to execute the "openssl" client program - and both lag behind GNU TLS with their X.509 certificate handling APIs which are just as important as doing the crypto.

So sorry, but right now we have no plans of adopting OpenSSL (again) for CUPS. *Maybe* LibreSSL, but we still need to resolve how we handle X.509 certificates.

**Comment by kloczek** [comment]
> OpenSSL support was removed from CUPS many years ago due to numerous security issues in OpenSSL at the time along with the relatively primitive and fragile API that is provided. OpenSSL's only advantage in the crypto field was that it was the first free implementation, which is why so many programs (CUPS included) added TLS support using it

Yes buut that was looong time ago and in mean time openssl code quality improved so much that it started dominating as mainly used crypto/TLS ABI.

> I am actually a big fan of the LibreSSL project

As long as it is fork of openssl I suppoe that on API layer it will be openssl compliant. If I'm right possiblity to build cups with openssl or LibreSSL supprt could be only different on autoconf level.
If that is not the case adding yet anotehr crypto/TLS API support would be kind of waste of time because AFAIK none of the Linuix or other Unixes distros is using LibreSSL on massive scale,

**Comment by kloczek** [comment]
Why not keeptrhat opened if someone will come with patch and/or to encourage someone to start working on that?
