### ISSUE TITLE
中文支持是否可行 (Is Chinese support possible?)

### ISSUE THREAD

**Issue by lpfxh** [OpenPrinting/cups#843]
能否添加中文语言支持，或者如何设置成中文语言

**Comment by michaelrsweet** [comment]
English translation:

> Can Chinese language support be added, or how to set it to Chinese language?

**Comment by michaelrsweet** [comment]
The current CUPS sources include a Simplified Chinese (`zh_CN` aka `zh-Hans`) translation, and various Linux distros provide additional translations/localizations. Internally CUPS will convert the different locale names to `zh_CN` or `zh_TW` since those (legacy) names have been in use for a long time...

**Comment by szlt5** [comment]
CUPS目前是支持中文的，若你安装的PPD中有中文的翻译。那么在你打印的时候，应用程序是可以显示成中文的。
比如我附件的这样。

[c1.pdf](https://github.com/OpenPrinting/cups/files/13655337/c1.pdf)

**Comment by michaelrsweet** [comment]
Translation:

> CUPS currently supports Chinese, if the PPD you install has Chinese translation. Then when you print, the application can display it in Chinese. For example, this is what I attached.

**Comment by zdohnal** [comment]
CUPS itself supports Chinese and translations from PPDs depend on driver provider whether he will provide the translations.
One of the perks of IPP Everywhere printing is that those strings are generated based on IPP response, so CUPS can provide translation for them - otherwise it is up to the driver provider.

If the PPD you use is part of CUPS project, you can send a PR with Chinese translations and we can accept it, otherwise there is no Chinese speaker here to give the translation.
