### ISSUE TITLE
making cupsfilter command more user friendly

### ISSUE THREAD

**Issue by surajkulriya** [OpenPrinting/cups#87]
When using command cupsfilter if we mistakenly type command 
`usr/sbin/cupsfilter -p <ppd-file> -m `
it tells the usage of cupsfilter command. Shouldn't we tell the user that it expects `destination mime type` after `-m` option.
Similar things for other options as well.
Another feature we can add is that spacing may or may not require between option-value pair, like `-mapplication/pdf` should also be valid.

**Comment by michaelrsweet** [comment]
@surajkulriya Support for the old-style "-ovalue" options is limited to the legacy Berkeley and System V printing commands. Modern command-line processing does not support it because it does not allow for unambiguous stringing of options.

As for the error reporting, most CUPS commands *do* show a specific error message when an option expects an argument but it looks like cupsfilter was never updated with localized messages.

**Comment by michaelrsweet** [comment]
Resolved by PR#88 from @surajkulriya :)
