### ISSUE TITLE
Shared IPP printer reports only a single resolution in `pwg-raster-document-resolution-supported`

### ISSUE THREAD

**Issue by ValdikSS** [OpenPrinting/cups#901]
**Describe the bug**

Similar to #445, but for shared printers.

When the printer is shared over IPP, `pwg-raster-document-resolution-supported` value is filled only with a single resolution (a first one in PPD file) and not a set of resolutions, and it is NOT a default resolution.

If the PPD file contains a list of resolutions from lower to higher, only the first lower one would be advertised in `pwg-raster-document-resolution-supported`.

```
$ ipptool -tv 'ipp://uowprint.local:631/printers/HP_LaserJet_M1005' get-printer-attributes.test | grep 'resolution)'
        printer-resolution-supported (1setOf resolution) = 600dpi,1200dpi
        pwg-raster-document-resolution-supported (resolution) = 600dpi
        printer-resolution-default (resolution) = 1200dpi
```

https://github.com/OpenPrinting/cups/blob/c220e7836b700563516e152ce629ff59b1b23de7/scheduler/printers.c#L4678-L4683

**To Reproduce**
1. Add a PPD file which lists resolutions from lower to higher
2. Run ipptool to check the resolutions

**Expected behavior**

`pwg-raster-document-resolution-supported` field contains a set (array) of resolutions, not a single resolution.

**System Information:**
 - CUPS version: from v2.2b1 to current git master c220e7836b700563516e152ce629ff59b1b23de7

**Comment by michaelrsweet** [comment]
With respect, it is worthless to list PWG Raster resolutions beyond 720dpi, and in fact most real IPP Everywhere/AirPrint printers don't support input raster beyond 720dpi. The very slight improvement in edge detail is matched with a 4x increase in print data size that dramatically affects print speed and resource usage...

Conceptually we should be listing all resolutions <= 720dpi, but the current code just lists the first resolution in the PPD file for simplicity since basically all CUPS servers support (vector) PDF which is preferred over raster data by Android, ChromeOS, iOS, Linux, macOS, and Windows clients...

Will see if I can come up with something for CUPS 2.5, but I'm not going to worry about backporting to 2.4.x since the raster path is rarely used...

**Comment by kabassanov** [comment]
Hmmm, isn't it what is used to define pdftops resolution (defaulting to -r600) even for printers allowing resolutions of 1200dpi?

**Comment by michaelrsweet** [comment]
[master 31ab57dd1] Update cupsd code to report all supported raster resolutions (Issue #901)
