### ISSUE TITLE
Deprecate Kerberos support

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups#98]
Need to document that Kerberos support in CUPS is deprecated starting with CUPS 2.4.0.

**Comment by krumboeck** [comment]
May I ask, why Kerberos is deprecated? Is Samba now the only way to get a good Windows domain integration?
Will CUPS support any other SSO authentication mechanism (or in near future)?

best regards,
Bernd

**Comment by michaelrsweet** [comment]
@krumboeck Kerberos is deprecated because Microsoft has moved to OAuth.

Samba remains the only way to integrate Windows clients with CUPS print queues, or for CUPS clients to print to Windows print queues that aren't offered through their Universal Print Service (which is IPP + OAuth).

*Kerberos will continue to work in CUPS 2.4.* And OAuth support is being added as the new SSO mechanism in CUPS 2.4 as well.

**Comment by mikhailnov** [comment]
Hm, what about Linux-based domains (FreeIPA for example)?

**Comment by michaelrsweet** [comment]
@mikhailnov Those will need to migrate as well, which is one of the reasons we try to announce deprecations as far in advance as we can.

**Comment by olaf-b** [comment]
Stumbled on this post. I'm confused as to the argument for dropping it. I presume it has less to do with Kerberos, and more to do with legacy Windows print queues being deprecated? Certainly, Kerberos itself is alive and well, and not deprecated by Microsoft universally.

**Comment by olaf-b** [comment]
Hmmm. Don't really recognize your description. Issues in AD, elevation and forwarding, yes. But otherwise I'd disagree. Kerberos can be pretty solid. Anyway, I was just curious of the more details of the rationale.

**Comment by k1ll3rb1z** [comment]
Hello,
I'm using openprinting cups 2.4.7-2 on archlinux and it works with kerberos authentication after some efforts, because cups launches /usr/lib/cups/backend/smb (linked to /sbin/smbspool) wrapper as the user nobody which prevents kerberos authentication.

A possible solution is:
- to give nobody the right to launch smbspool as the user which needs to authenticate via /etc/sudoers (nobody ALL=(theuser) NOPASSWD: /sbin/smbspool
- add theuser in the nobody group so he can access the file to print
- then link /usr/lib/cups/backend/smb to a bash script which launch smbspool as "theuser":

#!/bin/bash
sudo -u theuser /sbin/smbspool smb://<printing server>/<Printer> "$@"

It would be better if cups could just the run /usr/lib/cups/backend/smb as the job owner.

**Comment by k1ll3rb1z** [comment]
I tried that also but the magic never happened.
Cheers,
